import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../domain/entities/content.dart';

class LibraryState {
  final List<Content> contents;
  final List<ContentCategory> categories;
  final bool isLoading;
  final String? error;
  
  const LibraryState({
    this.contents = const [],
    this.categories = const [],
    this.isLoading = false,
    this.error,
  });
  
  LibraryState copyWith({
    List<Content>? contents,
    List<ContentCategory>? categories,
    bool? isLoading,
    String? error,
  }) {
    return LibraryState(
      contents: contents ?? this.contents,
      categories: categories ?? this.categories,
      isLoading: isLoading ?? this.isLoading,
      error: error,
    );
  }
}

class LibraryNotifier extends StateNotifier<LibraryState> {
  LibraryNotifier() : super(const LibraryState()) {
    loadContents();
  }
  
  Future<void> loadContents() async {
    state = state.copyWith(isLoading: true);
    
    // Simulate API call
    await Future.delayed(const Duration(milliseconds: 300));
    
    final contents = _allContents;
    
    state = state.copyWith(
      contents: contents,
      isLoading: false,
    );
  }
}

final libraryProvider = StateNotifierProvider<LibraryNotifier, LibraryState>((ref) {
  return LibraryNotifier();
});

// Selected content type filter
final selectedContentTypeProvider = StateProvider<ContentType?>((ref) => null);

// ── Content Data ──────────────────────────────────────────────────────────

const _allContents = <Content>[

  // ── Breathing ─────────────────────────────────────────────────────────
  Content(
    id: 'br1',
    title: '4-7-8 Breathing',
    description: 'A calming breath technique where you inhale for 4 counts, hold for 7, and exhale for 8. This pattern activates your parasympathetic nervous system, easing tension and preparing your body for rest.',
    type: ContentType.breathing,
    durationSeconds: 180,
    tags: ['beginner', 'calm', 'sleep-aid'],
    steps: [
      'Sit or lie down comfortably',
      'Exhale completely through your mouth',
      'Inhale quietly through your nose for 4 counts',
      'Hold your breath for 7 counts',
      'Exhale fully through your mouth for 8 counts',
      'Repeat the cycle 4 times',
    ],
  ),
  Content(
    id: 'br2',
    title: 'Box Breathing',
    description: 'Also known as square breathing, this technique uses four equal phases — inhale, hold, exhale, hold — to create balance and focus. Used by Navy SEALs and athletes to stay calm under pressure.',
    type: ContentType.breathing,
    durationSeconds: 240,
    tags: ['focus', 'stress-relief', 'intermediate'],
    steps: [
      'Find a quiet place and sit upright',
      'Breathe in slowly through your nose for 4 counts',
      'Hold your breath gently for 4 counts',
      'Exhale slowly through your mouth for 4 counts',
      'Hold with empty lungs for 4 counts',
      'Repeat for 4–6 cycles',
    ],
  ),
  Content(
    id: 'br3',
    title: 'Diaphragmatic Breathing',
    description: 'Learn to breathe from your belly instead of your chest. This foundational technique strengthens your diaphragm, reduces your breathing rate, and helps you feel more grounded throughout the day.',
    type: ContentType.breathing,
    durationSeconds: 300,
    tags: ['foundational', 'wellbeing', 'beginner'],
    steps: [
      'Lie on your back with knees bent',
      'Place one hand on your chest, one on your belly',
      'Breathe in through your nose for 4 counts',
      'Feel your belly rise while your chest stays still',
      'Exhale slowly through pursed lips for 6 counts',
      'Practice for 5–10 minutes daily',
    ],
  ),
  Content(
    id: 'br4',
    title: 'Alternate Nostril Breathing',
    description: 'A classic yogic practice that balances the left and right hemispheres of your brain. This gentle technique promotes mental clarity and a sense of inner calm, perfect for moments of scattered thoughts.',
    type: ContentType.breathing,
    durationSeconds: 360,
    tags: ['balance', 'clarity', 'yoga'],
    steps: [
      'Sit comfortably with a tall spine',
      'Use your right thumb to close your right nostril',
      'Inhale through the left nostril for 4 counts',
      'Close both nostrils and hold for 2 counts',
      'Release the right nostril, exhale for 4 counts',
      'Inhale through the right nostril, then alternate',
    ],
  ),
  Content(
    id: 'br5',
    title: 'Lion\'s Breath',
    description: 'An energizing breath that releases tension from your face and chest. You inhale deeply and exhale with a forceful "ha" sound while sticking out your tongue. Great for shaking off stress and boosting confidence.',
    type: ContentType.breathing,
    durationSeconds: 120,
    tags: ['energizing', 'release', 'fun'],
    steps: [
      'Sit in a comfortable kneeling or cross-legged position',
      'Place your palms on your knees with fingers spread wide',
      'Inhale deeply through your nose',
      'Open your mouth wide and stick out your tongue',
      'Exhale forcefully with a "ha" sound',
      'Repeat 5–7 times',
    ],
  ),
  Content(
    id: 'br6',
    title: 'Ocean Breath',
    description: 'Known as Ujjayi in yoga, this technique creates a soft ocean-like sound in the back of your throat. It warms the breath, anchors your attention, and builds a soothing rhythm for meditation or movement.',
    type: ContentType.breathing,
    durationSeconds: 300,
    tags: ['soothing', 'meditation', 'yoga'],
    steps: [
      'Sit tall and relax your shoulders',
      'Breathe in through your nose slowly',
      'Slightly constrict the back of your throat',
      'Create a gentle whispering sound as you inhale',
      'Exhale through your nose with the same sound',
      'Continue for 5 minutes at a steady pace',
    ],
  ),
  Content(
    id: 'br7',
    title: 'Resonance Breathing',
    description: 'Breathe at a rate of about 5–6 breaths per minute to synchronize with your heart rate variability. This scientifically-backed technique reduces anxiety and promotes deep physiological relaxation.',
    type: ContentType.breathing,
    durationSeconds: 360,
    tags: ['science-backed', 'anxiety', 'advanced'],
    steps: [
      'Sit comfortably and close your eyes',
      'Inhale gently for 5 seconds',
      'Exhale slowly for 5 seconds',
      'Focus on the smooth transition between inhale and exhale',
      'Maintain this rhythm without straining',
      'Practice for 5–10 minutes',
    ],
  ),

  // ── Movement / Stretch ────────────────────────────────────────────────
  Content(
    id: 'mv1',
    title: 'Morning Wake-Up Stretch',
    description: 'A gentle 10-minute sequence to release overnight stiffness and wake up your body. Includes neck rolls, shoulder shrugs, spinal twists, and a full-body reach. Start every morning with intention and ease.',
    type: ContentType.stretch,
    durationSeconds: 600,
    tags: ['morning', 'flexibility', 'beginner'],
    steps: [
      'Start seated on the edge of your bed',
      'Roll your neck slowly in circles, 5 times each direction',
      'Shrug your shoulders up to your ears and release, 10 times',
      'Interlace fingers and reach overhead, stretching both sides',
      'Twist gently to the left and right, holding each side 15 seconds',
      'Stand and fold forward, letting your arms hang naturally',
      'Slowly roll up to standing, reaching for the sky',
    ],
  ),
  Content(
    id: 'mv2',
    title: 'Evening Walk Meditation',
    description: 'Transform your evening stroll into a mindful walking practice. Focus on the sensation of your feet touching the ground and the rhythm of your steps. A perfect bridge between a busy day and a peaceful evening.',
    type: ContentType.stretch,
    durationSeconds: 900,
    tags: ['mindful', 'outdoor', 'stress-relief'],
    steps: [
      'Step outside and take three deep breaths',
      'Begin walking at a natural, unhurried pace',
      'Notice the feeling of each foot as it lifts, moves, and lands',
      'If your mind wanders, gently return to the sensation of walking',
      'Take in the sounds, smells, and sights around you',
      'End with three slow breaths and a moment of gratitude',
    ],
  ),
  Content(
    id: 'mv3',
    title: 'Desk Worker Release',
    description: 'Counteract the effects of sitting all day with this targeted sequence. Focus on releasing tension in your neck, shoulders, chest, and hip flexors. No mat or equipment needed — perfect for your workspace.',
    type: ContentType.stretch,
    durationSeconds: 420,
    tags: ['office', 'posture', 'quick'],
    steps: [
      'Sit tall and roll your shoulders backward 10 times',
      'Clasp hands behind your head and open your elbows wide',
      'Interlace fingers, push palms forward, round your upper back',
      'Stand and do a gentle standing quad stretch, each side 20 seconds',
      'Place one ankle on the opposite knee and lean forward for a hip opener',
      'Repeat the hip stretch on the other side',
    ],
  ),
  Content(
    id: 'mv4',
    title: 'Sun Salutation Flow',
    description: 'A classical yoga sequence that warms the entire body and links breath with movement. This flowing practice builds strength, flexibility, and mindful awareness — a complete practice in just a few minutes.',
    type: ContentType.stretch,
    durationSeconds: 480,
    tags: ['yoga', 'energy', 'intermediate'],
    steps: [
      'Stand tall with hands at heart center — Mountain Pose',
      'Inhale, sweep arms overhead — Upward Salute',
      'Exhale, fold forward — Standing Forward Bend',
      'Inhale, lift your halfway — Half Lift',
      'Exhale, step or jump back to Plank, lower to the floor',
      'Inhale to Cobra, exhale to Downward Dog',
      'Walk or jump feet to hands, repeat 3–5 rounds',
    ],
  ),
  Content(
    id: 'mv5',
    title: 'Bedtime Gentle Yoga',
    description: 'A soothing floor-based practice designed to unwind your body before sleep. Slow movements, long holds, and deep breathing signal your nervous system that it is time to rest. Best done in dim lighting.',
    type: ContentType.stretch,
    durationSeconds: 600,
    tags: ['evening', 'relaxation', 'sleep'],
    steps: [
      'Begin on hands and knees — Cat-Cow stretches, 10 breaths',
      'Move into Child\'s Pose, breathing deeply for 1 minute',
      'Sit back, extend both legs — Seated Forward Fold, 1 minute',
      'Lie on your back — bring knees to chest, gently rock side to side',
      'Supine twist: drop both knees to one side, hold 1 minute each',
      'Savasana: lie flat, arms at your sides, breathe naturally for 2 minutes',
    ],
  ),
  Content(
    id: 'mv6',
    title: 'Tai Chi for Beginners',
    description: 'Experience the meditative flow of Tai Chi with this gentle introductory practice. Slow, continuous movements improve balance, reduce stress, and cultivate a deep sense of inner calm and body awareness.',
    type: ContentType.stretch,
    durationSeconds: 600,
    tags: ['tai-chi', 'balance', 'mindfulness'],
    steps: [
      'Stand with feet shoulder-width apart, knees slightly bent',
      'Raise your hands slowly in front of your chest — "Parting the Wild Horse\'s Mane"',
      'Shift weight to the left, extend right arm forward and left arm back',
      'Flow into "White Crane Spreads Its Wings" — shift, lift, extend',
      'Move through "Brush Knee" — turn, shift, and push gently',
      'Repeat the sequence slowly, matching breath to movement',
    ],
  ),
  Content(
    id: 'mv7',
    title: '5-Minute Energy Boost',
    description: 'When you need a quick pick-me-up, this dynamic stretch sequence increases blood flow and wakes up your muscles. Jumping jacks, arm circles, lunges, and torso twists — no coffee required.',
    type: ContentType.stretch,
    durationSeconds: 300,
    tags: ['quick', 'energy', 'beginner'],
    steps: [
      'Start with 30 seconds of gentle jumping jacks',
      'Arm circles forward 15 times, then backward 15 times',
      'Alternate side lunges, 10 each side',
      'Standing torso twists, 10 each direction',
      'High knees in place for 20 seconds',
      'Shake out your arms and legs, take 3 deep breaths',
    ],
  ),

  // ── Herbal Tea / Tea Ritual ───────────────────────────────────────────
  Content(
    id: 'tea1',
    title: 'Chamomile Sunset',
    description: 'The classic evening companion. Chamomile flowers deliver gentle apigenin, a natural compound that supports relaxation. Sip slowly while dimming the lights and let the warmth carry you toward a peaceful night.',
    type: ContentType.teaRitual,
    durationSeconds: 600,
    tags: ['evening', 'sleep', 'calming'],
    steps: [
      'Heat water to 95°C (just below boiling)',
      'Place 2–3 teaspoons of dried chamomile flowers in a teapot',
      'Pour water over the flowers and cover',
      'Steep for 5 minutes — longer makes it more calming',
      'Strain into your favorite cup',
      'Optional: add a thin slice of lemon or a drizzle of honey',
    ],
  ),
  Content(
    id: 'tea2',
    title: 'Peppermint Clarity',
    description: 'A refreshing, cooling brew that awakens the senses and supports digestion. Peppermint leaves contain menthol, which helps open your airways and sharpen your focus. Perfect for mid-afternoon slumps.',
    type: ContentType.teaRitual,
    durationSeconds: 420,
    tags: ['focus', 'digestion', 'refreshing'],
    steps: [
      'Bring fresh water to a rolling boil',
      'Add a generous handful of fresh peppermint leaves to a mug',
      'Pour boiling water directly over the leaves',
      'Cover and steep for 7 minutes',
      'Remove leaves or strain',
      'Enjoy hot or pour over ice for a cool version',
    ],
  ),
  Content(
    id: 'tea3',
    title: 'Ginger Lemon Vitality',
    description: 'A warming, immune-supporting blend that kicks your morning into gear. Fresh ginger root pairs with bright lemon to create a spicy-sweet tonic that awakens your body and lifts your spirit.',
    type: ContentType.teaRitual,
    durationSeconds: 480,
    tags: ['morning', 'immunity', 'warming'],
    steps: [
      'Peel and thinly slice a 2-inch piece of fresh ginger',
      'Add ginger slices to a small pot with 2 cups of water',
      'Simmer on low heat for 10 minutes',
      'Pour into a mug and squeeze in half a lemon',
      'Add honey to taste if desired',
      'Stir well and sip slowly to begin your day',
    ],
  ),
  Content(
    id: 'tea4',
    title: 'Ceremonial Matcha',
    description: 'A meditative tea practice rooted in Japanese tradition. Stone-ground green tea powder delivers calm, focused energy through L-theanine and gentle caffeine. Whisk mindfully — the ritual is as nourishing as the tea itself.',
    type: ContentType.teaRitual,
    durationSeconds: 600,
    tags: ['ritual', 'focus', 'energy'],
    steps: [
      'Sift 1–2 teaspoons of ceremonial-grade matcha into a bowl',
      'Add a small splash of 80°C water',
      'Whisk briskly in an "M" shape with a bamboo chasen until frothy',
      'Top up with more warm water to your preference',
      'Hold the bowl with both hands, take a slow breath',
      'Sip mindfully, noticing the earthy, umami flavor',
    ],
  ),
  Content(
    id: 'tea5',
    title: 'Lavender Honey Dream',
    description: 'A fragrant, floral blend designed to ease you into restful sleep. Lavender has been used for centuries to calm the nervous system, while raw honey adds a touch of natural sweetness and comfort.',
    type: ContentType.teaRitual,
    durationSeconds: 540,
    tags: ['sleep', 'floral', 'comforting'],
    steps: [
      'Heat water to 90°C',
      'Combine 1 teaspoon dried lavender with 1 teaspoon chamomile',
      'Pour water over the herbs and steep for 5 minutes',
      'Strain into a warm mug',
      'Stir in 1 teaspoon of raw honey until dissolved',
      'Drink 30–60 minutes before bedtime',
    ],
  ),
  Content(
    id: 'tea6',
    title: 'Turmeric Golden Milk',
    description: 'A creamy, anti-inflammatory elixir inspired by Ayurvedic tradition. Turmeric, black pepper, and warm milk create a golden drink that soothes your body from the inside out. A hug in a mug.',
    type: ContentType.teaRitual,
    durationSeconds: 480,
    tags: ['anti-inflammatory', 'evening', 'ayurvedic'],
    steps: [
      'Warm 1 cup of your preferred milk (oat, almond, or dairy)',
      'Add 1 teaspoon turmeric powder and a pinch of black pepper',
      'Add ½ teaspoon cinnamon and a small piece of fresh ginger',
      'Simmer gently for 3–4 minutes, stirring frequently',
      'Strain into your favorite mug',
      'Sweeten with honey or maple syrup to taste',
    ],
  ),
  Content(
    id: 'tea7',
    title: 'Jasmine Green Serenity',
    description: 'Delicate jasmine blossoms layered over green tea leaves create a soothing, aromatic experience. This elegant blend encourages gentle alertness while melting away stress. Ideal for mindful afternoon pauses.',
    type: ContentType.teaRitual,
    durationSeconds: 360,
    tags: ['afternoon', 'mindfulness', 'elegant'],
    steps: [
      'Warm your teapot and cup with hot water, then empty',
      'Add 1 teaspoon of jasmine green tea leaves',
      'Pour water at 80°C over the leaves',
      'Steep for 2–3 minutes — no longer, to avoid bitterness',
      'Pour slowly and appreciate the floral aroma',
      'Take the first sip with your eyes closed',
    ],
  ),

  // ── Sleep ─────────────────────────────────────────────────────────────
  Content(
    id: 'sl1',
    title: 'Sleep Hygiene Essentials',
    description: 'Build the foundation for great sleep with science-backed habits. From consistent bedtimes to screen curfews, these small adjustments make a big difference in your sleep quality and morning energy.',
    type: ContentType.sleep,
    durationSeconds: 300,
    tags: ['foundational', 'habits', 'science-backed'],
    steps: [
      'Set a consistent bedtime and wake time, even on weekends',
      'Stop looking at screens 60 minutes before bed',
      'Keep your bedroom cool, between 18–20°C',
      'Use blackout curtains or a sleep mask for darkness',
      'Reserve your bed for sleep and intimacy only',
      'Avoid caffeine after 2 PM and heavy meals before bed',
    ],
  ),
  Content(
    id: 'sl2',
    title: 'Progressive Muscle Relaxation',
    description: 'Systematically tense and release each muscle group to dissolve physical tension. This technique is one of the most effective ways to transition from a wired mind to a rest-ready body. Often used in sleep clinics worldwide.',
    type: ContentType.sleep,
    durationSeconds: 600,
    tags: ['technique', 'relaxation', 'effective'],
    steps: [
      'Lie in bed, close your eyes, and take 3 slow breaths',
      'Starting at your feet, tense the muscles for 5 seconds',
      'Release suddenly and notice the contrast — complete relaxation',
      'Move to your calves: tense, hold, release',
      'Continue through thighs, stomach, chest, arms, hands',
      'Finish with your face: scrunch, hold, release. Feel the difference.',
    ],
  ),
  Content(
    id: 'sl3',
    title: 'Evening Wind-Down Ritual',
    description: 'Create a sacred transition between day and night. A structured wind-down ritual signals your brain that sleep is approaching. This multi-sensory practice combines touch, scent, sound, and gentle movement.',
    type: ContentType.sleep,
    durationSeconds: 900,
    tags: ['ritual', 'evening', 'holistic'],
    steps: [
      '60 minutes before bed: dim all lights in your home',
      'Prepare a cup of chamomile or lavender tea',
      'Light a candle or diffuse calming essential oils',
      'Journal for 5 minutes — write down anything on your mind',
      'Do 5 minutes of gentle stretching or restorative yoga',
      'Get into bed and practice 4-7-8 breathing until you drift off',
    ],
  ),
  Content(
    id: 'sl4',
    title: 'Body Scan for Sleep',
    description: 'A guided awareness practice that takes you on a mental tour of your body. By gently noticing each region without trying to change anything, you naturally release tension and drift into a deep, restful state.',
    type: ContentType.sleep,
    durationSeconds: 900,
    tags: ['meditation', 'guided', 'deep-rest'],
    steps: [
      'Lie comfortably and close your eyes',
      'Bring attention to the top of your head — notice any sensation',
      'Slowly scan down: forehead, eyes, cheeks, jaw — let each soften',
      'Move to neck and shoulders — invite them to release',
      'Continue through your chest, belly, hips, legs, and feet',
      'When you reach your toes, let go completely and allow sleep to come',
    ],
  ),
  Content(
    id: 'sl5',
    title: 'Rain Sounds Meditation',
    description: 'Immerse yourself in the soothing rhythm of rainfall. Close your eyes and picture each drop as it lands, creating a natural white noise that masks distracting thoughts. A favorite among those who struggle with racing minds at night.',
    type: ContentType.sleep,
    durationSeconds: 1800,
    tags: ['nature', 'audio', 'calming'],
    isPremium: true,
    steps: [
      'Put on your headphones or play through a speaker',
      'Set the volume to a gentle, background level',
      'Close your eyes and visualize rain falling softly',
      'Notice the rhythm — it is never perfectly even, and that is okay',
      'Let the sound fill the space between your thoughts',
      'Allow yourself to drift — there is nothing else to do right now',
    ],
  ),
  Content(
    id: 'sl6',
    title: 'Counting Breath Technique',
    description: 'When your mind refuses to quiet down, give it a simple, repetitive task. Counting your exhalations occupies just enough mental bandwidth to prevent anxious spiraling while gently guiding you toward sleep.',
    type: ContentType.sleep,
    durationSeconds: 600,
    tags: ['technique', 'anxiety', 'simple'],
    steps: [
      'Lie in bed and breathe naturally for a few breaths',
      'On the next exhale, silently count "one"',
      'Inhale, then on the exhale, count "two"',
      'Continue counting each exhale up to ten',
      'If you lose count, start again at one — no frustration',
      'Most people drift off before reaching ten repeatedly',
    ],
  ),
  Content(
    id: 'sl7',
    title: 'Gratitude & Sleep Connection',
    description: 'Research shows that a brief gratitude practice before bed improves sleep quality and reduces the time it takes to fall asleep. End each day by acknowledging the good, no matter how small it may seem.',
    type: ContentType.sleep,
    durationSeconds: 300,
    tags: ['gratitude', 'science-backed', 'mindset'],
    steps: [
      'Get into bed and get comfortable',
      'Think of three specific things from today you are grateful for',
      'For each one, close your eyes and relive the moment briefly',
      'Notice the warm feeling that gratitude creates in your body',
      'Place one hand on your heart and take 3 slow breaths',
      'Let the feeling of gratitude carry you into sleep',
    ],
  ),

  // ── Meditation ────────────────────────────────────────────────────────
  Content(
    id: 'md1',
    title: 'Body Scan Meditation',
    description: 'A foundational mindfulness practice that builds interoceptive awareness. By gently directing attention through each region of your body, you cultivate a deep sense of presence and learn to release tension you did not know you were holding.',
    type: ContentType.meditation,
    durationSeconds: 1200,
    tags: ['foundational', 'awareness', 'relaxation'],
    steps: [
      'Find a comfortable seated or lying position',
      'Close your eyes and take 3 deep, settling breaths',
      'Bring your attention to the crown of your head',
      'Slowly move your focus downward, part by part',
      'Notice sensations without judging — warmth, tingling, numbness',
      'If you find tension, breathe into it and let it soften',
      'When you reach your feet, rest in the awareness of your whole body',
    ],
  ),
  Content(
    id: 'md2',
    title: 'Loving-Kindness Meditation',
    description: 'Also known as Metta, this heart-centered practice cultivates compassion — starting with yourself and expanding outward. Research shows it increases positive emotions, reduces self-criticism, and strengthens your sense of connection to others.',
    type: ContentType.meditation,
    durationSeconds: 900,
    tags: ['compassion', 'heart', 'emotional'],
    steps: [
      'Sit comfortably and close your eyes, hands over your heart',
      'Silently repeat: "May I be happy. May I be healthy. May I be at peace."',
      'Think of someone you love. Repeat the phrases for them',
      'Extend to a neutral person — a neighbor, a stranger',
      'Include someone you find difficult — this is where growth happens',
      'Finish by offering these wishes to all beings everywhere',
    ],
  ),
  Content(
    id: 'md3',
    title: 'Nature Visualization',
    description: 'Escape to a peaceful natural setting through guided imagery. This meditation uses your imagination to transport you to a calming environment — a forest, a beach, a meadow — activating the same relaxation response as being there in person.',
    type: ContentType.meditation,
    durationSeconds: 600,
    tags: ['visualization', 'nature', 'calm'],
    steps: [
      'Close your eyes and take 5 slow breaths',
      'Imagine yourself walking through a quiet forest',
      'Notice the dappled sunlight filtering through the trees',
      'Feel the soft earth beneath your feet',
      'Hear birdsong and the gentle rustle of leaves',
      'Find a clearing, sit down, and simply rest in this peace',
    ],
  ),
  Content(
    id: 'md4',
    title: 'Mindful Breathing Anchor',
    description: 'The simplest and most portable meditation. Whenever you feel overwhelmed, return to the breath as your anchor. This practice trains your attention like a muscle — the more you practice, the calmer your default state becomes.',
    type: ContentType.meditation,
    durationSeconds: 480,
    tags: ['beginner', 'focus', 'portable'],
    steps: [
      'Sit comfortably and set a timer for 8 minutes',
      'Close your eyes or soften your gaze downward',
      'Bring your full attention to where you feel the breath most',
      'This might be your nostrils, chest, or belly — follow it',
      'When your mind wanders (it will), gently return to the breath',
      'Each return is not a failure — it is the practice itself',
    ],
  ),
  Content(
    id: 'md5',
    title: 'Walking Meditation',
    description: 'Meditation does not require stillness. In this practice, each step becomes an anchor for awareness. Walking meditation is ideal for those who find sitting still challenging and brings mindfulness into everyday movement.',
    type: ContentType.meditation,
    durationSeconds: 600,
    tags: ['movement', 'outdoor', 'accessible'],
    steps: [
      'Find a quiet path or clear space, 20–30 steps long',
      'Stand still, feel your feet on the ground, take 3 breaths',
      'Begin walking very slowly — lift, move, place, feel',
      'Notice the shift of weight from one foot to the other',
      'When you reach the end, pause, breathe, and turn mindfully',
      'Continue for 10 minutes, keeping attention on the soles of your feet',
    ],
  ),
  Content(
    id: 'md6',
    title: 'Gratitude Meditation',
    description: 'Shift your perspective from what is missing to what is present. This meditation gently guides you to notice and savor the blessings in your life — from the simplest pleasures to the deepest connections — cultivating lasting contentment.',
    type: ContentType.meditation,
    durationSeconds: 600,
    tags: ['gratitude', 'positivity', 'perspective'],
    steps: [
      'Sit comfortably and close your eyes',
      'Bring to mind someone who has been kind to you recently',
      'Hold that person in your awareness and feel gratitude arise',
      'Expand to something simple: the warmth of sunlight, a good meal',
      'Let the feeling of thankfulness fill your chest',
      'Rest in this warmth for several breaths before opening your eyes',
    ],
  ),
  Content(
    id: 'md7',
    title: 'Mountain Meditation',
    description: 'Inspired by the steadfast mountain, this practice cultivates inner stability. Visualize yourself as a mountain — grounded, unshakeable, yet open to whatever weather passes through. A powerful metaphor for emotional resilience.',
    type: ContentType.meditation,
    durationSeconds: 720,
    tags: ['resilience', 'visualization', 'grounding'],
    isPremium: true,
    steps: [
      'Sit comfortably with a tall, dignified posture',
      'Close your eyes and visualize a grand mountain',
      'Notice how the mountain sits — solid, still, ancient',
      'The weather changes around it: sun, rain, snow, wind',
      'The mountain remains. It does not resist or chase the weather',
      'Identify with the mountain — let your thoughts and feelings be the weather',
    ],
  ),

  // ── Reflection / Journaling ───────────────────────────────────────────
  Content(
    id: 'rf1',
    title: 'Gratitude Journal',
    description: 'A daily practice of identifying three things you are grateful for. Studies from positive psychology show that consistent gratitude journaling increases happiness, improves sleep, and strengthens relationships over just 21 days.',
    type: ContentType.reflection,
    durationSeconds: 300,
    tags: ['gratitude', 'daily', 'science-backed'],
    steps: [
      'Open your journal at the same time each day',
      'Write "Today I am grateful for..." at the top',
      'List three specific things — be detailed, not generic',
      'For each one, write one sentence about why it matters to you',
      'Notice how you feel as you write — let it be genuine',
      'Close the journal and carry this warmth with you',
    ],
  ),
  Content(
    id: 'rf2',
    title: 'Mood Check-In',
    description: 'Develop emotional awareness by pausing to identify and name your current feelings. Research shows that labeling emotions reduces their intensity — a process psychologists call "affect labeling." Just 2 minutes of honest self-reflection.',
    type: ContentType.reflection,
    durationSeconds: 180,
    tags: ['emotional-awareness', 'quick', 'daily'],
    steps: [
      'Pause wherever you are and take a slow breath',
      'Ask yourself: "What am I feeling right now?"',
      'Try to name the emotion specifically — not just "fine" or "okay"',
      'Notice where you feel it in your body — chest, stomach, jaw',
      'Ask: "What might be causing this feeling?" without judging',
      'Acknowledge it, write it down if you can, and let it be',
    ],
  ),
  Content(
    id: 'rf3',
    title: 'Weekly Reflection Prompts',
    description: 'Dedicate time each week to look back and look forward. These carefully crafted prompts help you recognize growth, celebrate small wins, and set intentional direction. Self-reflection is the compass for a meaningful life.',
    type: ContentType.reflection,
    durationSeconds: 600,
    tags: ['weekly', 'growth', 'intentional'],
    steps: [
      'What was the most meaningful moment of my week?',
      'What challenged me, and how did I respond?',
      'What am I most proud of from this week?',
      'Is there something I am avoiding that needs attention?',
      'What do I want to focus on next week?',
      'Write freely — this is for your eyes only',
    ],
  ),
  Content(
    id: 'rf4',
    title: 'Letting Go Exercise',
    description: 'A structured journaling practice for releasing thoughts, worries, or feelings that are weighing you down. By writing them down and symbolically releasing them, you create mental space for what truly matters.',
    type: ContentType.reflection,
    durationSeconds: 480,
    tags: ['release', 'emotional', 'therapeutic'],
    steps: [
      'Write at the top: "I am ready to let go of..."',
      'List everything that is on your mind — worries, grudges, fears',
      'For each item, write one sentence about why you are holding on',
      'Now write: "I acknowledge this, and I choose to release it."',
      'Read the list aloud slowly, then tear out or erase the page',
      'Take a deep breath — the slate is clean',
    ],
  ),
  Content(
    id: 'rf5',
    title: 'Intention Setting',
    description: 'Move beyond to-do lists and set meaningful intentions that align with your values. Unlike rigid goals, intentions are about how you want to show up — they are flexible, compassionate, and deeply personal.',
    type: ContentType.reflection,
    durationSeconds: 420,
    tags: ['intention', 'values', 'purposeful'],
    steps: [
      'Sit quietly and ask: "How do I want to feel today?"',
      'Choose one word or short phrase that captures this feeling',
      'Write it down: "My intention today is to be [your word]."',
      'Visualize yourself moving through the day with this intention',
      'Place the note somewhere you will see it — mirror, desk, phone',
      'At the end of the day, reflect: did I honor this intention?',
    ],
  ),
  Content(
    id: 'rf6',
    title: 'Letter to Your Future Self',
    description: 'Write a letter to who you will be in six months or one year. This powerful exercise builds self-compassion, clarifies your aspirations, and creates a tangible connection between your present efforts and your future wellbeing.',
    type: ContentType.reflection,
    durationSeconds: 600,
    tags: ['future', 'aspiration', 'self-compassion'],
    steps: [
      'Date the letter and address it: "Dear [Your Name] in [future date]..."',
      'Describe your current life honestly — the joys and the struggles',
      'Share what you are working on and what you hope will change',
      'Write words of encouragement — be as kind as you would to a friend',
      'Seal the envelope and set a calendar reminder to open it',
      'When the day comes, read it with curiosity and compassion',
    ],
  ),
  Content(
    id: 'rf7',
    title: 'Mindful Moments Log',
    description: 'Train yourself to notice the small, beautiful moments that pass unnoticed. This practice sharpens your attention to the present and builds a personal archive of joy. Over time, you will start noticing more of these moments naturally.',
    type: ContentType.reflection,
    durationSeconds: 180,
    tags: ['mindfulness', 'joy', 'daily'],
    steps: [
      'Keep a small notebook or note on your phone',
      'Throughout the day, pause when something makes you smile',
      'Note the moment: "The way sunlight hit my coffee this morning."',
      'Include sensory details — what did you see, hear, feel, smell?',
      'At the end of the day, review your moments — smile again',
      'Over weeks, watch your collection of ordinary beauty grow',
    ],
  ),

  // ── Stories ───────────────────────────────────────────────────────────
  Content(
    id: 'st1',
    title: 'The Quiet Garden',
    description: 'Drift into a peaceful garden where time moves slowly and every flower tells a story. This gentle narration guides you through a lush, sensory landscape — perfect for unwinding after a long day or easing into sleep.',
    type: ContentType.story,
    durationSeconds: 1200,
    tags: ['sleep', 'nature', 'narration'],
    isPremium: true,
    steps: [
      'Find a comfortable position, close your eyes',
      'Imagine a wooden gate opening into a sunlit garden',
      'Walk slowly along a path lined with lavender and roses',
      'Notice the warm breeze carrying sweet floral scents',
      'Find a stone bench beneath an old oak tree',
      'Sit, breathe, and let the garden\'s peace wash over you',
    ],
  ),
  Content(
    id: 'st2',
    title: 'Journey to the Stars',
    description: 'A cosmic bedtime story that carries you beyond the atmosphere on a gentle voyage through the universe. Soft-spoken narration and vivid imagery make this a favorite for both children and adults who love looking up at the night sky.',
    type: ContentType.story,
    durationSeconds: 1500,
    tags: ['sleep', 'adventure', 'wonder'],
    isPremium: true,
    steps: [
      'Lie down and imagine lying on soft grass on a clear night',
      'Look up at thousands of twinkling stars',
      'Feel yourself gently floating upward, weightless and free',
      'Drift past the moon, feeling its cool silver light',
      'Travel slowly through constellations, each one a story',
      'Find a quiet nebula, wrap yourself in stardust, and rest',
    ],
  ),
  Content(
    id: 'st3',
    title: 'The Lantern Festival',
    description: 'A comforting tale set in a small village where thousands of lanterns float into the night sky, each carrying a wish. Let this warm, communal imagery fill you with hope and connection as you prepare for sleep.',
    type: ContentType.story,
    durationSeconds: 1200,
    tags: ['sleep', 'cultural', 'comforting'],
    steps: [
      'Imagine arriving at a quiet village at twilight',
      'People are gathering, each holding a paper lantern',
      'You receive a lantern — what wish will you write on it?',
      'The lanterns begin to rise, filling the sky with warm light',
      'Watch them float higher, carrying hopes and dreams into the stars',
      'Your lantern joins them, and you feel lighter as you drift to sleep',
    ],
  ),
];
