"""
SEASONS Audio Content Library v2 — Real hosted audio files
Audio files hosted at: http://116.62.32.43/static/audio/{lang}/
"""

AUDIO_BASE_URL = "http://116.62.32.43/static/audio"

# Each entry has: en_url, zh_url
# The language-appropriate URL is selected by the API based on ?lang= query param
# Falls back to English if no lang specified

BREATHING = [
    {"id": "audio_breathe_1", "title": "4-7-8 Breathing", "subtitle": "A calming breath to ease anxiety", "use_case": "Before sleep or during stressful moments", "duration_minutes": 5, "best_time": "evening", "type": "guided", "tags": ["anxiety", "sleep", "calm"], "is_premium": False, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_breathe_1.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_breathe_1.mp3"},
    {"id": "audio_breathe_2", "title": "Box Breathing", "subtitle": "Equal counts for emotional balance", "use_case": "When you need to center yourself", "duration_minutes": 4, "best_time": "any", "type": "guided", "tags": ["focus", "balance"], "is_premium": False, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_breathe_2.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_breathe_2.mp3"},
    {"id": "audio_breathe_3", "title": "Morning Breath Reset", "subtitle": "Start the day with intention", "use_case": "First thing in the morning", "duration_minutes": 3, "best_time": "morning", "type": "guided", "tags": ["morning", "energy"], "is_premium": False, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_breathe_3.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_breathe_3.mp3"},
    {"id": "audio_breathe_4", "title": "Deep Belly Breathing", "subtitle": "Activate your rest system", "use_case": "When feeling overwhelmed", "duration_minutes": 6, "best_time": "afternoon", "type": "guided", "tags": ["relaxation", "stress"], "is_premium": True, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_breathe_4.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_breathe_4.mp3"},
    {"id": "audio_breathe_5", "title": "Alternate Nostril Breathing", "subtitle": "Balancing breath from yoga", "use_case": "Transition between tasks", "duration_minutes": 5, "best_time": "any", "type": "guided", "tags": ["balance", "focus"], "is_premium": True, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_breathe_5.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_breathe_5.mp3"},
]

WIND_DOWN = [
    {"id": "audio_wind_1", "title": "Evening Wind-Down", "subtitle": "A gentle transition from day to night", "use_case": "30-60 minutes before bed", "duration_minutes": 8, "best_time": "evening", "type": "guided", "tags": ["sleep", "evening"], "is_premium": False, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_1.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_1.mp3"},
    {"id": "audio_wind_2", "title": "Body Scan for Sleep", "subtitle": "Release tension from head to toe", "use_case": "In bed, lights off", "duration_minutes": 10, "best_time": "evening", "type": "guided", "tags": ["sleep", "relaxation"], "is_premium": True, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_2.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_2.mp3"},
    {"id": "audio_wind_3", "title": "Gratitude Reflection", "subtitle": "End the day with appreciation", "use_case": "Evening journaling companion", "duration_minutes": 5, "best_time": "evening", "type": "guided", "tags": ["reflection", "gratitude"], "is_premium": False, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_3.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_3.mp3"},
    {"id": "audio_wind_4", "title": "Progressive Relaxation", "subtitle": "Tense and release for deep calm", "use_case": "When you can't fall asleep", "duration_minutes": 12, "best_time": "evening", "type": "guided", "tags": ["sleep", "tension"], "is_premium": True, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_4.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_4.mp3"},
]

SEASONAL = [
    {"id": "audio_season_spring", "title": "Spring Renewal", "subtitle": "Embrace the season of new beginnings", "use_case": "Spring mornings", "duration_minutes": 8, "best_time": "morning", "type": "guided", "tags": ["spring", "renewal"], "is_premium": True, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_spring.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_spring.mp3"},
    {"id": "audio_season_summer", "title": "Summer Energy", "subtitle": "Stay cool and centered in the heat", "use_case": "Summer afternoons", "duration_minutes": 6, "best_time": "afternoon", "type": "guided", "tags": ["summer", "balance"], "is_premium": True, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_summer.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_summer.mp3"},
    {"id": "audio_season_autumn", "title": "Autumn Letting Go", "subtitle": "A meditation for the season of release", "use_case": "Autumn evenings", "duration_minutes": 10, "best_time": "evening", "type": "guided", "tags": ["autumn", "release"], "is_premium": True, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_autumn.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_autumn.mp3"},
    {"id": "audio_season_winter", "title": "Winter Stillness", "subtitle": "Find warmth in the quiet", "use_case": "Winter nights", "duration_minutes": 12, "best_time": "evening", "type": "guided", "tags": ["winter", "stillness"], "is_premium": True, "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_winter.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_winter.mp3"},
]

SOUNDSCAPES = [
    # These use existing ambient sound files from static/audio/
    {"id": "audio_sound_1", "title": "Gentle Rain", "subtitle": "Steady rainfall for focus or sleep", "use_case": "Background while working or sleeping", "duration_minutes": 60, "best_time": "any", "type": "soundscape", "tags": ["focus", "sleep"], "is_premium": False, "en_url": f"{AUDIO_BASE_URL}/rain_30s.wav", "zh_url": f"{AUDIO_BASE_URL}/rain_30s.wav"},
    {"id": "audio_sound_2", "title": "Forest Morning", "subtitle": "Birds and gentle breeze", "use_case": "Morning routine or meditation", "duration_minutes": 30, "best_time": "morning", "type": "soundscape", "tags": ["nature", "morning"], "is_premium": False, "en_url": f"{AUDIO_BASE_URL}/forest_30s.wav", "zh_url": f"{AUDIO_BASE_URL}/forest_30s.wav"},
    {"id": "audio_sound_3", "title": "Ocean Waves", "subtitle": "Rhythmic waves for deep relaxation", "use_case": "Sleep or deep work", "duration_minutes": 90, "best_time": "any", "type": "soundscape", "tags": ["sleep", "relaxation"], "is_premium": True, "en_url": f"{AUDIO_BASE_URL}/ocean_30s.wav", "zh_url": f"{AUDIO_BASE_URL}/ocean_30s.wav"},
    {"id": "audio_sound_4", "title": "Crackling Fire", "subtitle": "Cozy warmth by the fire", "use_case": "Autumn/winter evenings", "duration_minutes": 45, "best_time": "evening", "type": "soundscape", "tags": ["cozy", "evening"], "is_premium": True, "en_url": f"{AUDIO_BASE_URL}/fire_30s.wav", "zh_url": f"{AUDIO_BASE_URL}/fire_30s.wav"},
]

AUDIO_LIBRARY = {
    "breathing": BREATHING,
    "wind_down": WIND_DOWN,
    "seasonal": SEASONAL,
    "soundscapes": SOUNDSCAPES,
}


def get_audio_url(item: dict, lang: str = "en") -> str:
    """Return the appropriate URL for the requested language."""
    if lang == "zh":
        return item.get("zh_url", item["en_url"])
    return item["en_url"]


def serialize_item(item: dict, lang: str = "en") -> dict:
    """Return API-safe item with correct audio_url for language."""
    result = {k: v for k, v in item.items() if k not in ("en_url", "zh_url")}
    result["audio_url"] = get_audio_url(item, lang)
    return result

# =====================================================================
# TEA RITUAL content (茶饮) — added 2026-03-22
# =====================================================================
TEA_RITUAL = [
    {"id": "tea_1", "title": "Chamomile Calm", "subtitle": "A soothing chamomile ritual to ease the mind", "use_case": "Evening wind-down or before sleep", "season": "any", "best_time": "evening", "type": "tea_ritual", "mood": "calm", "ingredients": ["1 tbsp dried chamomile flowers", "1 cup hot water (90°C)", "Optional: 1 tsp honey"], "steps": ["Heat water to 90°C and pour over chamomile.", "Cover and steep for 5 minutes.", "Strain and enjoy slowly.", "Breathe deeply with each sip."], "ritual_tip": "Place your hands around the warm cup before drinking. Feel the heat transfer.", "tags": ["calm", "sleep", "evening"], "is_premium": False, "closing_line": "Let the warmth settle you into the evening.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_breathe_1.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_breathe_1.mp3"},
    {"id": "tea_2", "title": "Mint Clarity", "subtitle": "Refresh and awaken with crisp peppermint", "use_case": "Morning clarity or afternoon reset", "season": "summer", "best_time": "morning", "type": "tea_ritual", "mood": "refreshed", "ingredients": ["6-8 fresh mint leaves", "1 cup hot water", "Optional: slice of lemon"], "steps": ["Rinse mint leaves gently.", "Pour hot water over leaves.", "Steep 3-5 minutes.", "Sip and notice the menthol clarity."], "ritual_tip": "Take three deep breaths before your first sip. Set an intention for the day.", "tags": ["clarity", "energy", "morning"], "is_premium": False, "closing_line": "Carry this clarity into your day.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_breathe_3.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_breathe_3.mp3"},
    {"id": "tea_3", "title": "Ginger Lemon Warmth", "subtitle": "A warming blend to support digestion and immunity", "use_case": "Cold weather or when feeling run down", "season": "winter", "best_time": "afternoon", "type": "tea_ritual", "mood": "grounded", "ingredients": ["3 thin slices fresh ginger", "½ lemon, juiced", "1 cup hot water", "Optional: 1 tsp honey"], "steps": ["Slice ginger thinly for maximum surface area.", "Add ginger and lemon juice to hot water.", "Steep 5-7 minutes.", "Strain and sip slowly."], "ritual_tip": "Feel the warmth spreading from your core outward. Imagine it reaching every cell.", "tags": ["warming", "immunity", "digestion"], "is_premium": False, "closing_line": "You are supported from within.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_breathe_4.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_breathe_4.mp3"},
    {"id": "tea_4", "title": "Matcha Focus", "subtitle": "L-theanine balanced caffeine for calm alertness", "use_case": "Deep work sessions or creative projects", "season": "spring", "best_time": "morning", "type": "tea_ritual", "mood": "focused", "ingredients": ["1 tsp matcha powder", "2 oz hot water (80°C)", "6 oz frothed milk or plant milk"], "steps": ["Sift matcha into a bowl to remove clumps.", "Pour a small amount of hot water and whisk vigorously.", "Add milk and froth or whisk in a zigzag motion.", "Drink within 30 minutes of preparation."], "ritual_tip": "Whisk in a W motion — it activates the amino acids. Notice the aroma before drinking.", "tags": ["focus", "energy", "antioxidants"], "is_premium": True, "closing_line": "A clear mind ready to create.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_breathe_2.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_breathe_2.mp3"},
    {"id": "tea_5", "title": "Lavender Honey Dream", "subtitle": "A gentle sedative blend for restful sleep", "use_case": "Insomnia or restless nights", "season": "autumn", "best_time": "evening", "type": "tea_ritual", "mood": "drowsy", "ingredients": ["1 tsp dried lavender buds", "1 tsp honey", "1 cup hot water"], "steps": ["Steep lavender in hot water for 4 minutes.", "Strain into your favourite cup.", "Stir in honey until dissolved.", "Drink while sitting somewhere calm, then move to bed."], "ritual_tip": "Inhale the steam before drinking. Count 4 seconds in, 7 seconds hold, 8 seconds out.", "tags": ["sleep", "calm", "anxiety"], "is_premium": True, "closing_line": "Drift gently into rest.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_2.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_2.mp3"},
    {"id": "tea_6", "title": "Golden Milk Turmeric", "subtitle": "Anti-inflammatory evening elixir with warming spices", "use_case": "Before bed for inflammation or joint discomfort", "season": "winter", "best_time": "evening", "type": "tea_ritual", "mood": "soothing", "ingredients": ["1 cup milk or plant milk", "1 tsp turmeric", "½ tsp cinnamon", "Pinch of black pepper", "1 tsp honey"], "steps": ["Warm milk gently (do not boil).", "Whisk in turmeric, cinnamon, and black pepper.", "Continue stirring for 3 minutes.", "Remove from heat, stir in honey, and sip."], "ritual_tip": "Black pepper increases curcumin absorption by 2000%. This is a ritual of true self-care.", "tags": ["anti-inflammatory", "joint health", "warming"], "is_premium": True, "closing_line": "Your body thanks you for this kindness.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_4.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_4.mp3"},
]

# =====================================================================
# SLEEP content — added 2026-03-22
# =====================================================================
SLEEP_CONTENT = [
    {"id": "sleep_1", "title": "Sleep Hygiene Essentials", "subtitle": "Build a foundation for consistent, restorative sleep", "use_case": "Nightly routine building", "best_time": "evening", "type": "sleep", "environment_tip": "Keep bedroom at 18-20°C. Remove screens 30 min before bed. Use blackout curtains.", "steps": ["Set a consistent bedtime (same time daily).", "Begin wind-down routine 60 minutes before bed.", "Dim lights to signal melatonin production.", "Practice 5 minutes of box breathing in bed.", "If not asleep in 20 min, get up and return when sleepy."], "tags": ["sleep hygiene", "routine", "habit"], "is_premium": False, "closing_line": "Consistency is the compound interest of sleep.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_1.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_1.mp3"},
    {"id": "sleep_2", "title": "Progressive Muscle Relaxation", "subtitle": "Systematically release physical tension for deeper sleep", "use_case": "Racing mind or physical tension at bedtime", "best_time": "evening", "type": "sleep", "environment_tip": "Lie flat on your back. Keep room slightly cool. Use a heavy blanket if available.", "steps": ["Starting at your toes: tense for 5 seconds, then release.", "Move to calves, tense, release.", "Progress up: thighs, abdomen, hands, arms, shoulders, face.", "Notice the contrast between tension and relaxation.", "When finished, scan your body for any remaining tension and release it."], "tags": ["PMR", "tension release", "deep sleep"], "is_premium": True, "closing_line": "Your body knows how to rest. Let it.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_4.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_4.mp3"},
    {"id": "sleep_3", "title": "Body Scan for Sleep", "subtitle": "A mindful journey from toes to crown", "use_case": "In bed, unable to quiet the mind", "best_time": "evening", "type": "sleep", "environment_tip": "Lights off or very dim. Guided by breath, not by clock.", "steps": ["Lie comfortably and close your eyes.", "Bring attention to your feet: notice temperature, sensation.", "Slowly move attention upward: calves, knees, thighs.", "Continue to abdomen, chest, lower back.", "Finish at the crown of your head.", "Stay in this open awareness as sleep approaches."], "tags": ["body scan", "mindfulness", "awareness"], "is_premium": True, "closing_line": "You are exactly where you need to be.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_2.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_2.mp3"},
    {"id": "sleep_4", "title": "4-7-8 Sleep Technique", "subtitle": "Dr. Andrew Weil's calming breath for falling asleep", "use_case": "Acute insomnia or pre-flight nerves", "best_time": "evening", "type": "sleep", "environment_tip": "Use as a replacement for counting sheep. Works best after 2 weeks of practice.", "steps": ["Exhale completely through your mouth.", "Close mouth, inhale through nose for 4 counts.", "Hold breath for 7 counts.", "Exhale completely through mouth for 8 counts.", "Repeat for 4 cycles only."], "tags": ["4-7-8", "breathing", "insomnia"], "is_premium": False, "closing_line": "The breath is the remote control for your nervous system.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_breathe_1.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_breathe_1.mp3"},
    {"id": "sleep_5", "title": "Gratitude Wind-Down", "subtitle": "End the day by noticing what went right", "use_case": "Racing thoughts or day-residue stress at bedtime", "best_time": "evening", "type": "sleep", "environment_tip": "Keep a small notebook by the bed. Write briefly, don't editorialise.", "steps": ["In bed, eyes closed, take three deep breaths.", "Bring to mind one person or moment you are grateful for today.", "Notice how your body responds to the gratitude.", "Extend gratitude to yourself: one specific thing you did well.", "Let any remaining thoughts float by like clouds."], "tags": ["gratitude", "reflection", "sleep"], "is_premium": False, "closing_line": "Tomorrow is a continuation. Tonight, you have done enough.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_3.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_3.mp3"},
]

# =====================================================================
# SEASONAL LIVING content — added 2026-03-22
# =====================================================================
SEASONAL_LIVING = [
    {"id": "seasonal_1", "title": "Spring Renewal Practice", "subtitle": "Honor the energy of new beginnings", "season": "spring", "type": "seasonal", "how_it_feels": "A quiet excitement builds. Energy rises like sap in a tree. There is a desire to begin, to clear, to create.", "3_small_practices": ["Morning: Open a window and take 5 conscious breaths of fresh air.", "Midday: Eat one meal slowly and seasonally — something young and green.", "Evening: Write down one thing you want to plant this season."], "food_or_drink_suggestion": "Young barley grass tea, dafengmai congee, or sprouted mung beans.", "tags": ["spring", "renewal", "growth", "liver"], "is_premium": True, "closing_line": "Spring does not rush. Neither should you.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_spring.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_spring.mp3"},
    {"id": "seasonal_2", "title": "Summer Cooling Protocol", "subtitle": "Navigate the height of yang energy with balance", "season": "summer", "type": "seasonal", "how_it_feels": "Heat accumulates. The heart works hardest. There is vibrancy, but also a risk of excess. Cooling does not mean cold — it means balanced.", "3_small_practices": ["Morning: 10 minutes of gentle stretching before the sun is strong.", "Midday: Rest during the 11am-1pm hours when heart energy peaks.", "Evening: A short walk in nature as the temperature drops."], "food_or_drink_suggestion": "Watermelon, cucumber, lotus root tea, or mint lemonade. Avoid spicy, fried, or overly warming foods.", "tags": ["summer", "cooling", "heart", "yin"], "is_premium": True, "closing_line": "Summer asks you to shine, but also to rest.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_summer.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_summer.mp3"},
    {"id": "seasonal_3", "title": "Autumn Letting Go Ritual", "subtitle": "Align with the metal phase: harvest, grieve, and release", "season": "autumn", "type": "seasonal", "how_it_feels": "A bittersweet quality enters. The world shows us that endings are not failures — they are necessary. The lungs invite us to breathe deeply and release fully.", "3_small_practices": ["Morning: Name one thing you are ready to let go of. Write it on paper and burn it safely.", "Midday: Eat one warm, moist, slightly bitter food — such as brown rice or radish.", "Evening: 5 minutes of alternate nostril breathing to balance lung energy."], "food_or_drink_suggestion": "Pear or apple with honey, lotus seed congee, or white fungus soup.", "tags": ["autumn", "letting go", "lung", "metal"], "is_premium": True, "closing_line": "Autumn proves that emptiness is not loss — it is potential.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_autumn.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_autumn.mp3"},
    {"id": "seasonal_4", "title": "Winter Stillness Practice", "subtitle": "Turn inward during the most yin time of year", "season": "winter", "type": "seasonal", "how_it_feels": "The world contracts. Cold invites stillness. This is the season of the kidney — the source of our constitutional reserves. Rest is not laziness; it is wisdom.", "3_small_practices": ["Morning: Warm water with lemon before anything else.", "Midday: One warm, kidney-nourishing meal — black sesame, walnut, or bone broth.", "Evening: Abbreviate your evening routine. Sleep early. Let the darkness guide you to rest."], "food_or_drink_suggestion": "Black sesame porridge, walnut tea, mutton stew, or dried longan and goji broth.", "tags": ["winter", "stillness", "kidney", "yin"], "is_premium": True, "closing_line": "Winter is the compost pile. What seems dead is actually transforming.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_winter.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_winter.mp3"},
]

# Update the library dict with new categories
AUDIO_LIBRARY["tea_ritual"] = TEA_RITUAL
AUDIO_LIBRARY["sleep"] = SLEEP_CONTENT
AUDIO_LIBRARY["seasonal"] = SEASONAL_LIVING

# =====================================================================
# STRETCH content — added 2026-03-22
# =====================================================================
STRETCH = [
    {"id": "stretch_1", "title": "Morning Wake-Up Stretch", "subtitle": "Gentle stretches to greet the day with ease", "use_case": "First thing in the morning, before getting out of bed", "best_time": "morning", "type": "stretch", "body_focus": "Full body", "duration_minutes": 8, "caution": "Move slowly if you have neck issues.", "steps": ["Reach both arms overhead and stretch side to side.", "Gentle neck rolls — ear to shoulder, ear to shoulder.", "Cat-cow: arch and round the spine, 5 cycles.", "Seated spinal twist: hold each side 30 seconds.", "Finish with legs extended, reach for toes."], "tags": ["morning", "gentle", "full body"], "is_premium": False, "closing_line": "The day begins with how you meet yourself in the morning.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_spring.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_spring.mp3"},
    {"id": "stretch_2", "title": "Evening Wind-Down Walk", "subtitle": "A mindful walk to transition from day to night", "use_case": "After dinner, before the evening routine", "best_time": "evening", "type": "stretch", "body_focus": "Lower body and hips", "duration_minutes": 20, "caution": "Walk on flat, safe terrain. Reflective clothing if near traffic.", "steps": ["Start with 3 deep breaths before leaving.", "Walk at a pace that allows you to notice your surroundings.", "After 5 minutes, shift awareness to the sensation in your feet.", "After 10 minutes, begin to slow the pace gradually.", "Return home feeling gently transitioned into the evening."], "tags": ["evening", "mindful", "walking"], "is_premium": False, "closing_line": "A walk that marks the threshold between day and night.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_autumn.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_autumn.mp3"},
    {"id": "stretch_3", "title": "Desk Worker Reset", "subtitle": "Undo the damage of sitting for extended periods", "use_case": "Midday break or after long screen time", "best_time": "afternoon", "type": "stretch", "body_focus": "Neck, shoulders, upper back, hips", "duration_minutes": 5, "caution": "Stop if you feel sharp pain anywhere.", "steps": ["Shoulder shrugs: lift to ears, hold 3 seconds, release. Repeat 5 times.", "Chest opener: clasp hands behind back, lift, open chest. Hold 20 seconds.", "Seated hip stretch: one ankle over opposite knee, lean forward gently. Hold 30 sec each side.", "Neck stretch: drop ear to shoulder, use hand to add gentle pressure. 30 sec each side.", "Finish standing: roll shoulders back 5 times, big arm circles."], "tags": ["desk", "shoulders", "neck", "hips"], "is_premium": False, "closing_line": "Your body was not designed to sit this long. Give it what it needs.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_summer.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_summer.mp3"},
    {"id": "stretch_4", "title": "Sun Salutation Flow", "subtitle": "A classical yoga sequence to build heat and flexibility", "use_case": "Morning practice to energize the body", "best_time": "morning", "type": "stretch", "body_focus": "Full body", "duration_minutes": 15, "caution": "Skip or modify if you have wrist, knee, or back issues.", "steps": ["Mountain pose: stand tall, hands at heart, 3 breaths.", "Upward salute: inhale, sweep arms overhead.", "Forward fold: exhale, fold forward.", "Half lift: inhale, spine flat, eyes forward.", "Plank: exhale, lower to hover or full plank.", "Chaturanga: knees down or full, elbows close to ribs.", "Upward dog or cobra: inhale, chest forward.", "Downward dog: exhale, hips up, heels toward floor. Hold 5 breaths.", "Walk or jump feet to hands.", "Roll up to standing. Repeat 3-5 rounds."], "tags": ["yoga", "flow", "heat", "flexibility"], "is_premium": True, "closing_line": "You have created heat, space, and movement in the body.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_spring.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_spring.mp3"},
    {"id": "stretch_5", "title": "Bedtime Yoga", "subtitle": "Restorative poses to prepare the body for sleep", "use_case": "30 minutes before bed", "best_time": "evening", "type": "stretch", "body_focus": "Full body, nervous system", "duration_minutes": 10, "caution": "Use pillows for support. Never force a stretch.", "steps": ["Supine twist: knees to chest, drop both to right, gaze left. Hold 2 min each side.", "Legs up the wall: sit sideways to wall, swing legs up. Stay 3-5 min.", "Happy baby: on back, grab outer feet, rock gently. 2 min.", "Supported fish: pillow under upper back, arms open. Stay 3 min.", "Savasana: flat on back, palms up. Stay 3 min. Fall asleep if you can."], "tags": ["restorative", "sleep", "gentle", "nervous system"], "is_premium": False, "closing_line": "Let the floor hold you. You have done enough today.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_winter.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_winter.mp3"},
    {"id": "stretch_6", "title": "Tai Chi Morning Set", "subtitle": "A simple 10-minute Tai Chi routine for balance and calm", "use_case": "Morning practice for those who prefer slow, flowing movement", "best_time": "morning", "type": "stretch", "body_focus": "Balance, coordination, calm", "duration_minutes": 10, "caution": "Hold a wall or chair for the first few sessions if balance is unsteady.", "steps": ["Opening: stand in natural standing position. Breathe naturally.", "Arm circles: with exhale, float arms forward and up. Inhale, lower. 8 times.", "Ward off left and right: shift weight, one arm curves outward.", "Cloud hands: shift weight side to side, hands float like clouds. 16 shifts.", "Closing: gather qi back to the center. Rest in stillness for 1 minute."], "tags": ["tai chi", "balance", "slow", "morning"], "is_premium": True, "closing_line": "You have moved with the quality of water — yielding, patient, persistent.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_spring.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_spring.mp3"},
]

# =====================================================================
# REFLECTION content — added 2026-03-22
# =====================================================================
REFLECTION = [
    {"id": "reflection_1", "title": "Gratitude Check-In", "subtitle": "What are three things you are grateful for today?", "use_case": "Morning or evening journaling", "type": "reflection", "prompts": ["Name three things you are grateful for today.", "What is one small moment from today worth remembering?", "Who is one person you are grateful for, and why?"], "tags": ["gratitude", "daily", "positive"], "is_premium": False, "closing_line": "Gratitude is the most sustainable emotion. It compounds.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_3.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_3.mp3"},
    {"id": "reflection_2", "title": "Mood Check-In", "subtitle": "How are you really feeling right now?", "use_case": "Midday or evening emotional awareness", "type": "reflection", "prompts": ["On a scale of 1-10, how is your energy right now?", "What emotion is most present for you right now?", "What does your body need in this moment?"], "tags": ["emotion", "awareness", "self-care"], "is_premium": False, "closing_line": "Naming an emotion is the first step in working with it.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_2.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_2.mp3"},
    {"id": "reflection_3", "title": "Weekly Review", "subtitle": "Pause and look at the arc of your week", "use_case": "Sunday evening or end of week", "type": "reflection", "prompts": ["What went well this week? One specific moment.", "What was challenging? What did it teach you?", "What is one thing you want to do differently next week?", "What are you most proud of from these seven days?"], "tags": ["weekly", "review", "growth"], "is_premium": True, "closing_line": "Reflection is not rumination. It is the practice of learning from your own experience.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_spring.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_spring.mp3"},
    {"id": "reflection_4", "title": "Letting Go Practice", "subtitle": "What are you ready to release?", "use_case": "Seasonal transitions or moments of stuckness", "type": "reflection", "prompts": ["What is one thing I am holding onto that no longer serves me?", "If I let this go, what becomes possible?", "What is a small, concrete step I can take to begin releasing this?"], "tags": ["letting go", "autumn", "release", "transition"], "is_premium": True, "closing_line": "Autumn teaches us that letting go is not loss — it is the making of space.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_autumn.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_autumn.mp3"},
    {"id": "reflection_5", "title": "Intention Setting", "subtitle": "Plant a seed for the day or season ahead", "use_case": "Morning practice or new season beginning", "type": "reflection", "prompts": ["One word that captures how I want to feel today.", "One action that is aligned with my values.", "One thing I will do to be kind to myself today."], "tags": ["intention", "morning", "values", "focus"], "is_premium": False, "closing_line": "An intention is not a goal. It is a direction. You can return to it.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_season_spring.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_season_spring.mp3"},
    {"id": "reflection_6", "title": "Body Awareness Scan", "subtitle": "What is your body telling you today?", "use_case": "Any time, especially when stressed or disconnected", "type": "reflection", "prompts": ["Scan from head to toe: where do I feel sensation right now?", "Where am I holding tension? Can I breathe into it?", "What does my body need — movement, rest, water, warmth?"], "tags": ["body scan", "somatic", "awareness", "tension"], "is_premium": False, "closing_line": "The body keeps score. It is also the place where healing begins.", "en_url": f"{AUDIO_BASE_URL}/en-us/audio_wind_2.mp3", "zh_url": f"{AUDIO_BASE_URL}/zh-cn/audio_wind_2.mp3"},
]

# Add stretch and reflection to AUDIO_LIBRARY
AUDIO_LIBRARY["stretch"] = STRETCH
AUDIO_LIBRARY["reflection"] = REFLECTION
