import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // General
      'app_title': 'SEASONS',
      'loading': 'Loading...',
      'error': 'Something went wrong',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'next': 'Next',
      'skip': 'Skip',
      'back': 'Back',
      'done': 'Done',
      'close': 'Close',
      'search': 'Search',
      'get_started': 'Get Started',
      'learn_more': 'Learn More',
      'view_all': 'View All',
      'no_data': 'No data yet',
      'coming_soon': 'Coming Soon',

      // Navigation
      'nav_home': 'Home',
      'nav_seasons': 'Seasons',
      'nav_library': 'Library',
      'nav_profile': 'Profile',
      'nav_chat': 'Chat',
      'nav_wellness': 'Wellness',

      // Home
      'home_greeting_morning': 'Good Morning',
      'home_greeting_afternoon': 'Good Afternoon',
      'home_greeting_evening': 'Good Evening',
      'home_daily_insight': "Today's Insight",
      'home_suggestions': 'Gentle Suggestions',
      'home_chat_entry': 'Chat with Companion',
      'home_quick_questions': 'Quick Questions',
      'home_today_plan': "Today's Plan",
      'home_checkin': 'Daily Check-in',
      'home_streak': 'day streak',

      // Solar Terms / Seasons
      'solar_terms_title': 'Solar Terms',
      'solar_term_current': 'Current Term',
      'solar_term_detail': 'Term Details',
      'solar_wellness': 'Seasonal Wellness',
      'seasons_title': 'Seasons',
      'seasons_subtitle': 'Live with the rhythm of nature',
      'seasons_spring': 'Spring',
      'seasons_summer': 'Summer',
      'seasons_autumn': 'Autumn',
      'seasons_winter': 'Winter',
      'st_lichun': 'Start of Spring',
      'st_yushui': 'Rain Water',
      'st_jingzhe': 'Awakening of Insects',
      'st_chunfen': 'Spring Equinox',
      'st_qingming': 'Clear and Bright',
      'st_guyu': 'Grain Rain',
      'st_lixia': 'Start of Summer',
      'st_xiaoman': 'Grain Buds',
      'st_mangzhong': 'Grain in Ear',
      'st_xiazhi': 'Summer Solstice',
      'st_xiaoshu': 'Minor Heat',
      'st_dashu': 'Major Heat',
      'st_liqiu': 'Start of Autumn',
      'st_chushu': 'End of Heat',
      'st_bailu': 'White Dew',
      'st_qiufen': 'Autumn Equinox',
      'st_hanlu': 'Cold Dew',
      'st_shuangjiang': "Frost's Descent",
      'st_lidong': 'Start of Winter',
      'st_xiaoxue': 'Minor Snow',
      'st_daxue': 'Major Snow',
      'st_dongzhi': 'Winter Solstice',
      'st_xiaohan': 'Minor Cold',
      'st_dahan': 'Major Cold',

      // Chat
      'chat_title': 'Wellness Companion',
      'chat_placeholder': 'Share your thoughts...',
      'chat_companion': 'Companion',
      'chat_send': 'Send',
      'chat_new_conversation': 'New Conversation',
      'chat_history': 'Chat History',
      'chat_thinking': 'Thinking...',

      // Food Therapy
      'food_therapy': 'Food Therapy',
      'food_therapy_title': 'Seasonal Recipes',
      'food_recommend': 'Food Recommendations',
      'food_seasonal': 'Seasonal Ingredients',
      'food_recipe': 'Recipe',
      'food_ingredients': 'Ingredients',
      'food_steps': 'Steps',
      'food_benefits': 'Benefits',
      'tea_recommendation': 'Tea Recommendations',

      // Constitution / Body Type
      'constitution_title': 'Body Constitution',
      'constitution_test': 'Constitution Test',
      'constitution_result': 'Your Result',
      'constitution_report': 'Constitution Report',
      'body_type_neutral': 'Neutral',
      'body_type_qi_deficient': 'Qi Deficient',
      'body_type_yang_deficient': 'Yang Deficient',
      'body_type_yin_deficient': 'Yin Deficient',
      'body_type_phlegm': 'Phlegm-Dampness',
      'body_type_damp_heat': 'Damp-Heat',
      'body_type_blood_stasis': 'Blood Stasis',
      'body_type_qi_stagnation': 'Qi Stagnation',
      'body_type_special': 'Special Constitution',

      // Meditation & Exercise
      'meditation_title': 'Meditation',
      'meditation_focus': 'Focus Meditation',
      'meditation_sleep': 'Sleep Meditation',
      'meditation_body_scan': 'Body Scan',
      'exercise_title': 'Exercise',
      'exercise_baduanjin': 'Ba Duan Jin',
      'exercise_qigong': 'Qigong',
      'exercise_duration': 'Duration',
      'exercise_start': 'Start',
      'exercise_pause': 'Pause',
      'exercise_complete': 'Complete',

      // Library
      'library_title': 'Library',
      'library_subtitle': 'Curated wellness content',
      'library_articles': 'Articles',
      'library_videos': 'Videos',
      'library_audio': 'Audio',
      'library_favorites': 'Favorites',

      // Reflection / Journal
      'reflection_title': 'Reflection',
      'reflection_how_feeling': 'How are you feeling today?',
      'reflection_save': 'Save Reflection',
      'journal_title': 'Wellness Journal',
      'mood_title': 'Mood Tracker',
      'sleep_title': 'Sleep Tracker',
      'sleep_report': 'Sleep Report',

      // Profile & Settings
      'profile_title': 'Profile',
      'profile_edit': 'Edit Profile',
      'profile_setup': 'Set Up Profile',
      'settings_title': 'Settings',
      'settings_notification': 'Notifications',
      'settings_theme': 'Theme',
      'settings_language': 'Language',
      'settings_about': 'About',
      'settings_feedback': 'Feedback',
      'settings_privacy': 'Privacy Policy',
      'settings_terms': 'Terms of Service',
      'settings_logout': 'Log Out',
      'settings_delete_account': 'Delete Account',

      // Subscription
      'subscription_title': 'Subscription',
      'subscription_free': 'Free',
      'subscription_serenity': 'Serenity',
      'subscription_harmony': 'Harmony',
      'subscription_family': 'Family',
      'subscribe_title': 'Choose Your Plan',
      'subscribe_monthly': 'Monthly',
      'subscribe_yearly': 'Yearly',
      'subscribe_restore': 'Restore Purchase',
      'subscribe_manage': 'Manage Subscription',
      'premium_badge': 'Premium',
      'upgrade_prompt': 'Upgrade to unlock',

      // Family
      'family_title': 'Family Wellness',
      'family_invite': 'Invite Member',
      'family_members': 'Members',
      'family_add': 'Add Family Member',

      // Wellness
      'wellness_title': 'Wellness',
      'wellness_dashboard': 'Wellness Dashboard',
      'wellness_score': 'Wellness Score',
      'wellness_daily': 'Daily Wellness',
      'wellness_report': 'Wellness Report',
      'wellness_myth': 'Myth Buster',
      'acupoint_title': 'Acupressure Points',
      'meridian_title': 'Meridians',

      // Onboarding
      'onboarding_welcome': 'Welcome to SEASONS',
      'onboarding_subtitle': 'Your seasonal wellness companion',
      'onboarding_step1': 'Discover your constitution',
      'onboarding_step2': 'Get personalized plans',
      'onboarding_step3': 'Live in harmony with nature',

      // Auth
      'login_title': 'Log In',
      'register_title': 'Create Account',
      'login_email': 'Email',
      'login_password': 'Password',
      'login_forgot': 'Forgot Password?',
      'login_google': 'Continue with Google',
      'login_apple': 'Continue with Apple',
      'login_wechat': 'Continue with WeChat',
      'login_guest': 'Try as Guest',
      'login_no_account': "Don't have an account?",
      'login_has_account': 'Already have an account?',

      // Notifications
      'notification_title': 'Notifications',
      'notification_solar': 'Solar Term Reminder',
      'notification_checkin': 'Daily Check-in',
      'notification_wellness': 'Wellness Tip',

      // AI
      'ai_companion': 'AI Companion',
      'ai_generating': 'Generating...',
      'ai_disclaimer': 'This advice is for reference only and does not replace medical consultation.',

      // Time
      'time_morning': 'Morning',
      'time_afternoon': 'Afternoon',
      'time_evening': 'Evening',
      'time_night': 'Night',

      // Misc
      'share': 'Share',
      'feedback': 'Feedback',
      'help': 'Help',
      'version': 'Version',
      'copyright': '© 2026 SEASONS. All rights reserved.',

      // Home (additional)
      'home_wellness_principle': 'Wellness Principle',
      'home_ai_assistant': 'SEASONS AI Assistant',
      'home_reminder': 'SEASONS Reminder',
      'home_view_wellness_chart': 'View Full ShiChen Wellness Chart',
      'home_meridian_active': 'Meridian Active',

      // Profile (additional)
      'profile_brand': 'ShunShi AI',
      'profile_points': 'Points',
      'profile_coupons': 'Coupons',
      'profile_achievements': 'Achievements',
      'profile_invite_title': 'Invite a friend, get Premium',
      'profile_invite_subtitle': 'Walk with friends, enjoy wellness together',
      'profile_invite_now': 'Invite Now',
      'profile_wellness_goals': 'Wellness Goals',
      'profile_about': 'About SEASONS',
      'profile_slogan': 'Align with nature, nourish body and mind',
      'profile_guest_name': 'SEASONS Friend',
      'profile_free_tier': 'Free Tier',

      // Login (additional)
      'login_brand': 'Seasons',
      'login_subtitle': 'Live in harmony with nature',
      'login_full_name': 'Full name',
      'login_create_account': 'Create an account',
      'login_sign_in': 'Sign In',
      'login_or_continue_with': 'Or continue with',
      'login_skip': 'Skip for now',
      'login_error_empty': 'Please enter your email and password',
      'login_error_failed': 'Login failed. Please try again.',
      'login_error_fill_fields': 'Please fill in all fields',
      'login_error_register_failed': 'Registration failed. Please try again.',
      'login_error_guest_failed': 'Guest login failed. Please try again.',
      'login_google_sdk': 'Google Sign-In requires SDK setup',
      'login_apple_sdk': 'Apple Sign-In requires Apple Developer setup',

      // Solar (additional)
      'solar_days_until_next': '{days} days until next solar term',
      'solar_next': 'Next: {name}',
      'solar_d_away': '{count}d away',
      'solar_dietary_care': 'Dietary Care',
      'solar_exercise': 'Exercise',
      'solar_seasonal_teas': 'Seasonal Teas',

      // Constitution (additional)
      'constitution_quiz_empty': 'Questionnaire is empty, please try again later',
      'constitution_submit_failed': 'Submit failed: invalid data format',
      'constitution_report_locked': 'Unlock Full Report',
      'constitution_retake': 'Retake Test',
      'constitution_view_report': 'View Full Report',
      'constitution_start_test': 'Start Body Type Test',
      'constitution_your_type': 'Your Body Constitution',
      'constitution_characteristics': 'Characteristics',
      'constitution_diet_advice': 'Diet Advice',
      'constitution_exercise_advice': 'Exercise Advice',
      'constitution_daily_care': 'Daily Care',
      'constitution_emotional_care': 'Emotional Care',

      // Chat (additional)
      'chat_quota_used': 'Daily messages used up',
      'chat_upgrade_now': 'Upgrade Now',
      'chat_later': 'Later',
      'chat_health_notice': 'Health Safety Notice',
      'chat_understand': 'I Understand',

      // Settings (additional)
      'settings_push_notifications': 'Push Notifications',
      'settings_senior_mode': 'Senior Mode',
      'settings_senior_desc': 'Provides larger fonts and a simplified interface',
      'settings_clear_cache': 'Clear Cache',
      'settings_cloud_zen': 'Cloud & Water Zen',

      // Favorites
      'favorites_remove_failed': 'Failed to remove from favorites',

      // Feedback (additional)
      'feedback_type': 'Feedback Type',
      'feedback_rating': 'Rating',
      'feedback_content': 'Feedback Content',
      'feedback_submit_btn': 'Submit Feedback',
      'feedback_thanks': 'Thank you for your feedback!',

      // Family (additional)
      'family_no_members': 'No family members yet',
      'family_diff_plans': "Get differentiated wellness plans based on each person\'s body type",

      // Wellness (additional)
      'wellness_studio': 'Wellness Studio',
      'wellness_editors_picks': "Editor\'s Picks",

      // About
      'about_app_name': 'SEASONS · ShunShi',
      'about_version': 'Version 2.4.0',
      'about_description': 'SEASONS is an intelligent health companion based on TCM Wellness theory. Combining the 24 Solar Terms, 12 ShiChen periods, and 9 Body Types, it provides personalized wellness tips for every user.',

      // Meditation (additional)
      'meditation_breathing': 'Breathing into Change',
      'meditation_10min_grounding': '10 Min · Grounding',
      'meditation_atmosphere': 'Atmosphere Layer',
      'meditation_checkin': 'Check-in',

      // Checkin
      'checkin_sanctuary': 'Digital Sanctuary',
      'checkin_morning': 'Morning Stillness',
      'checkin_streak_current': 'Current Streak',
      'checkin_energy_question': 'How is your energy flowing today?',
      'checkin_energy_level': 'Energy Level',

      // Search
      'search_popular': 'Popular Search',

      // Subscription (additional)
      'subscription_recommended': 'RECOMMENDED',
      'subscription_annual_deal': 'Annual Deal',
      'subscription_per_year': '/yr',

      // Notification settings
      'notif_settings_title': 'Notification Settings',
      'solar_diet_wellness': 'Diet & Wellness',
      'solar_next_term': 'Next Solar Term: {name}',
      'exercise_type': 'Exercise Type',
      'exercise_all': 'All',
      'exercise_movement': 'Movement Breakdown',
      'exercise_start_ai': 'Start AI-Guided Practice',
      'exercise_no_content': 'No content yet',
      'achievement_3_8_unlocked': '3 / 8 Unlocked',
      'achievement_440_points_to_next_level': '440 points to next level',
      'achievement_achievement_badges': 'Achievement Badges',
      'achievement_current_level_beginner': 'Current Level: Beginner',
      'achievement_earned_glory': 'Earned Glory',
      'achievement_next_intermediate': 'Next: Intermediate',
      'achievement_path_to_mastery': 'Path to Mastery',
      'achievement_track_every_step_of_your_wellness_journey': 'Track every step of your wellness journey',
      'achievements_100day_commitment': '100-Day Commitment',
      'achievements_100day_wellness_challenge': '100-Day Wellness Challenge',
      'achievements_24_solar_terms_wellness': '24 Solar Terms Wellness',
      'achievements_community_star': 'Community Star',
      'achievements_complete_movement_set': 'Complete Movement Set',
      'achievements_early_riser': 'Early Riser',
      'achievements_food_therapy_expert': 'Food Therapy Expert',
      'achievements_practice_starter': 'Practice Starter',
      'achievements_solar_term_master': 'Solar Term Master',
      'bodytype_harmony_in_flux': '"Harmony in Flux"',
      'bodytype_solar_dominance': 'Solar Dominance',
      'bodytype_terrene_stability': 'Terrene Stability',
      'bodytype_your_essence': 'Your Essence',
      'bodytype_your_natural_rhythm': 'Your Natural Rhythm',
      'bodytype_your_seasonal_essence_balanced': 'Your Seasonal Essence: Balanced',
      'chat_now_broadcasting': 'Now broadcasting...',
      'chat_unlock': 'Unlock',
      'chatpagedart_4001619995_24h_mental_health_helpline': '400-161-9995 · 24h Mental Health Helpline',
      'chatpagedart_clear_chat': 'Clear Chat',
      'chatpagedart_crisis_hotline': 'Crisis Hotline',
      'chatpagedart_daily_free_messages_used_up': 'Daily free messages used up',
      'chatpagedart_follow_natural_rhythms_harmonize_body_and_min': 'Follow natural rhythms, harmonize body and mind',
      'chatpagedart_please_consult_a_medical_professional': 'Please consult a medical professional',
      'chatpagedart_quick_topics': 'Quick Topics',
      'chatpagedart_rest_routine': 'Rest & Routine',
      'chatpagedart_see_a_doctor': 'See a Doctor',
      'chatpagedart_sleep_early_rise_early_follow_natural_rhythms': 'Sleep early, rise early, follow natural rhythms',
      'chatpagedart_solar_term_care_tips': 'Solar Term Care Tips',
      'chatpagedart_try_snow_fungus_and_lily_bulb_to_moisten_dryn': 'Try snow fungus and lily bulb to moisten dryness',
      'chatpagedart_warm_companion': 'Warm Companion',
      'checkin_12_day_flow': '12 Day Flow',
      'checkin_checkin_saved': 'Check-in saved',
      'checkin_complete_checkin': 'Complete Check-in',
      'checkin_current_mood': 'Current Mood',
      'checkin_take_a_quiet_moment_to_listen_to_your_interna': 'Take a quiet moment to listen to your internal landscape.',
      'community_search_wellness_content': 'Search wellness content...',
      'community_seasons_ai_guidance': 'SEASONS AI Guidance',
      'community_seasons_shunshi': 'SEASONS ShunShi',
      'community_tip_focus_on_spring_liver_care': 'Tip: Focus on — Spring Liver care',
      'community_wellness_circle': 'Wellness Circle',
      'constitution_constitution_analysis': 'Constitution Analysis',
      'constitution_constitution_score': 'Constitution Score',
      'constitution_no_questions_available': 'No questions available',
      'constitution_retake_2': 'Retake',
      'constitution_wellness_tips': 'Wellness Tips',
      'constitution_your_constitution_type': 'Your Constitution Type',
      'constitutionrep_ai_wellness_rating': 'AI Wellness Rating',
      'constitutionrep_ai_wellness_summary': 'AI Wellness Summary',
      'constitutionrep_astragalus_chicken_soup': 'Astragalus Chicken Soup',
      'constitutionrep_baduanjin_regulate_spleen_stomach': 'Baduanjin · Regulate Spleen & Stomach',
      'constitutionrep_body_type_report': 'Body Type Report',
      'constitutionrep_body_type_score_distribution': 'Body Type Score Distribution',
      'constitutionrep_constitution_report_spring_equinox_2024': 'Constitution Report · Spring Equinox 2024',
      'constitutionrep_constitution_scores': 'Constitution Scores',
      'constitutionrep_constitution_strength': 'Constitution Strength',
      'constitutionrep_generate_care_calendar': 'Generate Care Calendar',
      'constitutionrep_generate_detailed_calendar': 'Generate Detailed Calendar',
      'constitutionrep_generate_wellness_calendar': 'Generate Wellness Calendar',
      'constitutionrep_generating_wellness_calendar': 'Generating wellness calendar...',
      'constitutionrep_personalized_care_plan': 'Personalized Care Plan',
      'constitutionrep_personalized_wellness_plan': 'Personalized Wellness Plan',
      'constitutionrep_recommended_acupoint': 'Recommended Acupoint',
      'constitutionrep_recommended_exercise': 'Recommended Exercise',
      'constitutionrep_recommended_recipe': 'Recommended Recipe',
      'constitutionrep_rest_the_body_move_the_qi': '"Rest the body, move the Qi."',
      'constitutionrep_rest_the_body_move_to_nourish_qi': '"Rest the body, move to nourish Qi."',
      'constitutionrep_start_cooking': 'Start Cooking',
      'constitutionrep_stillness_nourishes_the_body_movement_nourish': '"Stillness nourishes the body, movement nourishes Qi."',
      'constitutionrep_tonifies_qi_and_warms_the_middleideal_for_qi_': 'Tonifies Qi and warms the middle，Ideal for Qi Deficiency。',
      'constitutionrep_your_constitution': 'Your Constitution:',
      'constitutionrep_your_constitution_qi_deficient_with_phlegmdam': 'Your Constitution: Qi Deficient (with Phlegm-Damp)',
      'constitutionrep_zusanli_st36_tonify_middle_jiao_qi': 'Zusanli ST36 · Tonify Middle Jiao Qi',
      'diary_ai_insights': 'AI Insights',
      'diary_daily_rituals': 'Daily Rituals',
      'diary_diary_saved': 'Diary saved',
      'diary_follow_the_seasons_listen_to_your_body_rhythm': '"Follow the seasons, listen to your body rhythm."',
      'diary_good_morning_seasons_friend': 'Good morning, SEASONS friend',
      'diary_mood_map': 'Mood Map',
      'diary_no_data': 'No data',
      'diary_recent_entries': 'Recent Entries',
      'diary_save_diary': 'Save Diary',
      'diary_save_failed_please_retry': 'Save failed, please retry',
      'diary_sleep_quality': 'Sleep Quality',
      'diary_sleep_score': 'Sleep Score',
      'diary_try_this_tonight': 'Try this tonight',
      'diary_weekly_report': 'Weekly Report',
      'diary_wellness_diary': 'Wellness Diary',
      'diet_dietrecommended': 'Dietrecommended ',
      'diet_view': 'View',
      'discover_editors_choice': "Editor's Choice",
      'discover_featurededit': 'FeaturedEdit',
      'discover_no_relevant_results_found': 'No relevant results found',
      'discover_wellness_library': 'Wellness Library',
      'error_go_home': 'Go Home',
      'error_page_not_found': 'Page not found',
      'exercise_12min': '12min',
      'exercise_start_fullscreen_teaching': 'Start Full-Screen Teaching',
      'family_care_reminder_sent': 'Care reminder sent',
      'family_copy_invite_code': 'Copy Invite Code',
      'family_invite_code': 'Invite Code',
      'family_invite_code_copied_to_clipboard': 'Invite code copied to clipboard',
      'family_invite_content_copied_paste_and_send_to_famil': 'Invite content copied — paste and send to family member',
      'family_invite_family': 'Invite Family',
      'family_my_family': 'My Family',
      'family_send_care_reminder': 'Send Care Reminder',
      'family_share_with_family': 'Share with Family',
      'family_status_info': 'Status Info',
      'family_they_will_see_the_same_status_card': 'They will see the same status card',
      'family_view_profile_status_their_view': 'View Profile Status (Their View)',
      'food_health_insights': 'Health Insights',
      'food_want_to_learn_more': 'Want to learn more?',
      'growth_85_towards_harvest': '85% TOWARDS HARVEST',
      'growth_current_season': 'Current Season',
      'growth_gently_nurtured_achievements': 'Gently nurtured achievements',
      'growth_growth_milestones': 'Growth Milestones',
      'growth_journey_ahead': 'Journey Ahead',
      'growth_reflective_milestones': 'Reflective Milestones',
      'growth_spring_equinox_alignment': 'Spring Equinox Alignment',
      'growth_unlocked': 'Unlocked',
      'growth_your_growth_journey': 'Your Growth Journey',
      'guidance_body_type_insight': 'Body Type Insight',
      'guidance_daily_whisper': 'Daily Whisper',
      'guidance_deepen_insight': 'Deepen Insight',
      'guidance_flow_state': 'Flow State',
      'guidance_gentle_guidance': 'Gentle Guidance',
      'guidance_morning_ritual': 'Morning Ritual',
      'guidance_personalized_for_your_cycle': 'Personalized for your cycle',
      'guidance_seasonal_tip': 'Seasonal Tip',
      'guidance_vatapitta_balance': 'Vata-Pitta Balance',
      'home_12_days_until_qingming': '12 days until Qingming',
      'home_3_habits_completed_today': '3 habits completed today',
      'home_7dayfree': '7dayFree',
      'home_8_min_read': '8 min read',
      'home_a_glass_of_warm_water_the_first_step_to_nouri': 'A glass of warm water — the first step to nourishing Yang',
      'home_afternoon_wu_1113_wellness_continues': 'Afternoon Wu (11-13) — wellness continues',
      'home_ai_wellness_assistant': 'AI Wellness Assistant',
      'home_based_on_your_constitution': 'Based on your constitution',
      'home_check_in': 'Check In',
      'home_coming_soon': 'Coming soon',
      'home_consistency_bridges_intentions_and_health_kee': 'Consistency bridges intentions and health. Keep it up!',
      'home_constitution_assessment': 'Constitution Assessment',
      'home_dietary_wisdom': 'Dietary Wisdom',
      'home_dim_the_lights_20_minutes_earlier': 'Dim the lights 20 minutes earlier',
      'home_discover_your_body_type_for_personalized_well': 'Discover your body type for personalized wellness',
      'home_exclusive_body_type_plans_longterm_tracking_a': 'Exclusive Body Type Plans · Long-term Tracking · AI Insights',
      'home_explore_more': 'Explore More',
      'home_explore_principle': 'Explore Principle',
      'home_gentle_reminder': 'Gentle Reminder',
      'home_good_morning_seasons_friend': 'Good Morning, SEASONS Friend',
      'home_hai_2123_triple_burner_sleep_early_to_nourish': 'Hai (21-23) Triple Burner — sleep early to nourish Yin',
      'home_healing_sounds': 'Healing Sounds',
      'home_how_are_you_feeling_right_now': 'How are you feeling right now?',
      'home_huangdi_neijing': 'Huangdi Neijing',
      'home_log_water_intake': 'Log Water Intake →',
      'home_make_a_warm_drink_tonight': 'Make a warm drink tonight',
      'home_meditationqigong': 'MeditationQigong →',
      'home_meridian_clearing': 'Meridian Clearing',
      'home_mood': 'Mood',
      'home_mountain_streams_bamboo': 'Mountain Streams & Bamboo',
      'home_movement_practice': 'Movement Practice',
      'home_no_new_notifications': 'No new notifications',
      'home_nourish_yin_clear_heat_support_kidney_energy': 'Nourish yin, clear heat, support kidney energy',
      'home_personalized_guidance_for_this_season': 'Personalized guidance for this season',
      'home_philosophy_balance': 'Philosophy & Balance',
      'home_presleep_log': 'Pre-Sleep Log →',
      'home_quick_rituals': 'Quick Rituals',
      'home_read_more': 'Read More',
      'home_recommendations': 'Recommendations',
      'home_recommended_for_you': 'Recommended for You',
      'home_recorded_keep_it_up': 'Recorded! Keep it up 💪',
      'home_seasonal_library': 'Seasonal Library',
      'home_seasonal_rituals': 'Seasonal Rituals',
      'home_seasonal_tea': 'Seasonal Tea',
      'home_seasonal_wisdom': 'Seasonal Wisdom',
      'home_seasons_companion': 'SEASONS Companion',
      'home_see_all': 'See All',
      'home_solar_term_wellness_starts_from_morning': 'Solar Term Wellness starts from morning',
      'home_spring_vegetable_porridge': 'Spring Vegetable Porridge',
      'home_start_your_first_action_today': 'Start Your First Action Today',
      'home_submit_checkin': 'Submit Check-in',
      'home_submit_failed_please_retry': 'Submit failed, please retry',
      'home_take_a_walk': 'Take a Walk →',
      'home_take_three_slower_breaths': 'Take three slower breaths',
      'home_time_to_nourish_yin_prepare_for_sleep': 'Time to nourish Yin, prepare for sleep',
      'home_todays_rhythm': "Today's Rhythm",
      'home_track_mood_sleep_and_energy_patterns': 'Track mood, sleep, and energy patterns',
      'home_traditional_wellness_arts': 'Traditional Wellness Arts',
      'home_unlock_personalized_wellness': 'Unlock Personalized Wellness',
      'home_view_full_seasonal_guide': 'View Full Seasonal Guide',
      'home_view_seasonal_recipes': 'View Seasonal Recipes →',
      'home_water_reminder_complete_your_first_action_tod': 'Water Reminder → Complete your first action today',
      'home_wellness_focus': 'Wellness Focus',
      'home_what_would_you_like_to_record_today': 'What would you like to record today?',
      'home_xu_1921_pericardium_take_a_walk_to_relax_body': 'Xu (19-21) Pericardium — take a walk to relax body and mind',
      'ingredients_aligning_your_plate_with_the_rhythms_of_the_e': 'Aligning your plate with the rhythms of the earth.',
      'ingredients_body_type_alignment': 'Body Type Alignment',
      'ingredients_in_peak': 'In Peak',
      'ingredients_late_summer_harvest': 'Late Summer Harvest',
      'ingredients_search_ingredients': 'Search ingredients...',
      'ingredients_the_seasonal_directory': 'The Seasonal Directory',
      'ingredients_view_rituals': 'View Rituals',
      'ingredients_wellness_benefits': 'Wellness Benefits',
      'journal_current_internal_climate': 'Current Internal Climate',
      'journal_daily_gratitude': 'Daily Gratitude',
      'journal_harvesting_the_light': 'Harvesting the Light',
      'journal_late_summer_phase': 'Late Summer Phase',
      'journal_personal_intentions': 'Personal Intentions',
      'journal_prompt_what_are_you_shedding': 'Prompt: What are you shedding?',
      'journal_reflection_saved': 'Reflection saved',
      'journal_seasonal_reflection': 'Seasonal Reflection',
      'journal_write_your_reflection': 'Write your reflection...',
      'library_no_content_found_for_this_filter': 'No content found for this filter',
      'meridian_massage_steps': 'Massage Steps',
      'meridian_meridian_overview': 'Meridian Overview',
      'meridian_where_there_is_flow_there_is_no_pain': '"Where there is flow, there is no pain."',
      'movement_gentle_flow_ritual': 'Gentle Flow Ritual',
      'movement_late_summer_transition': 'Late Summer Transition',
      'movement_save_to_rituals': 'Save to Rituals',
      'movement_session_in_progress': 'Session in Progress',
      'movement_spatial_audio_active': 'Spatial Audio Active',
      'onboarding_start_experience': 'Start Experience',
      'profile_added_family_members': 'Added Family Members',
      'profile_ai_memory_cleared': 'AI memory cleared',
      'profile_all_data_deleted': 'All data deleted',
      'profile_all_data_has_been_deleted': 'All data has been deleted.',
      'profile_clear_ai_memory': 'Clear AI Memory?',
      'profile_clear_ai_memory_2': 'Clear AI Memory',
      'profile_clear_the_ai_assistant_memory': 'Clear the AI assistant memory',
      'profile_confirm_clear': 'Confirm Clear',
      'profile_confirm_deletion': 'Confirm Deletion',
      'profile_copy_invite_code_to_share_with_family': 'Copy invite code to share with family',
      'profile_data_exported_successfully': 'Data exported successfully',
      'profile_data_privacy': 'Data & Privacy',
      'profile_deactivate_calm_account': 'Deactivate Calm Account',
      'profile_delete_all_data': 'Delete All Data?',
      'profile_delete_all_data_2': 'Delete All Data',
      'profile_delete_all_my_data': 'Delete All My Data',
      'profile_deletion_failed': 'Deletion failed',
      'profile_describe_your_physical_condition_optional': 'Describe your physical condition (optional)',
      'profile_discover_your_body_type': 'Discover Your Body Type',
      'profile_download_all_your_personal_data_json_format': 'Download all your personal data (JSON format)',
      'profile_export_failed_please_retry': 'Export failed, please retry',
      'profile_export_my_data': 'Export My Data',
      'profile_family_management': 'Family Management',
      'profile_global_preferences': 'Global Preferences',
      'profile_hello_what_should_we_call_you': 'Hello, what should we call you?',
      'profile_hemisphere': 'Hemisphere',
      'profile_influences_seasonal_rituals_and_content': 'Influences seasonal rituals and content',
      'profile_invite_code_copied': 'Invite code copied',
      'profile_invite_family_to_wellness_together': 'Invite Family to Wellness Together',
      'profile_language_locale': 'Language & Locale',
      'profile_main_health_concerns_optional': 'Main health concerns (optional)',
      'profile_measurement_units': 'Measurement Units',
      'profile_no_family_members_added_yet': 'No family members added yet',
      'profile_not_sure_help_me_take_the_test': 'Not sure, help me take the test',
      'profile_nourishment_logic': 'Nourishment Logic',
      'profile_permanently_delete_all_your_data_irreversible': 'Permanently delete all your data (irreversible)',
      'profile_personalize_your_recipe_discovery_experience': 'Personalize your recipe discovery experience',
      'profile_privacyshunshiapp': 'privacy@shunshi.app',
      'profile_questions_about_your_data': 'Questions about your data?',
      'profile_seeker_of_calm': 'Seeker of Calm',
      'profile_select_your_primary_dialect': 'Select your primary dialect',
      'profile_select_your_tcm_body_type_to_get_personalized': 'Select your TCM Body Type to get personalized wellness tips',
      'profile_share_invite_code_to_add_family_members': 'Share invite code to add family members',
      'profile_sign_out_of_sanctuary': 'Sign Out of Sanctuary',
      'profile_spring_equinox_member_since_2023': 'Spring Equinox Member since 2023',
      'profile_thank_you_for_your_feedback_we_take_it_seriou': 'Thank you for your feedback — we take it seriously!',
      'profile_this_cannot_be_undone_all_data_will_be_perman': 'This cannot be undone. All data will be permanently deleted.',
      'profile_used_for_personalized_wellness_tips': 'Used for personalized wellness tips',
      'profile_used_to_recommend_wellness_plans_suitable_for': 'Used to recommend wellness plans suitable for your age',
      'profile_we_will_greet_you_by_this_name': 'We will greet you by this name',
      'profile_weight_distance_and_temperature': 'Weight, distance, and temperature',
      'profile_what_is_your_gender': 'What is your gender?',
      'profile_which_year_were_you_born_in': 'Which year were you born in?',
      'profile_your_data': 'Your Data',
      'records_avg_sleep': 'Avg Sleep',
      'records_mood_trends': 'Mood Trends',
      'records_quality_score': 'Quality Score',
      'records_sleep_stats': 'Sleep Stats',
      'records_today': 'Today',
      'records_wellnessrecords': 'WellnessRecords',
      'report_explore_your_late_spring_plan': 'Explore Your Late Spring Plan',
      'report_late_spring_focus': 'Late Spring Focus',
      'report_morning_sunlight': 'Morning Sunlight',
      'report_personal_assessment': 'Personal Assessment',
      'report_personalized_recommendation': 'Personalized Recommendation',
      'report_recommended': 'Recommended',
      'report_revised_may_12_2024': 'Revised May 12, 2024',
      'report_season_focus': 'Season Focus',
      'report_spring_equinox_week_3': 'Spring Equinox · Week 3',
      'settings_account_deleted_sorry_to_see_you_go': 'Account deleted. Sorry to see you go.',
      'settings_daily_checkin_reminder': 'Daily Check-in Reminder',
      'settings_daily_wellness_checkin_reminder': 'Daily wellness check-in reminder',
      'settings_data_export_ready_sharing_file': 'Data export ready. Sharing file...',
      'settings_email_us': 'Email Us',
      'settings_email_us_at_supportseasonsapp': 'Email us at support@seasons.app',
      'settings_exercise_reminder': 'Exercise Reminder',
      'settings_export_failed_please_try_again': 'Export failed. Please try again.',
      'settings_failed_to_delete_account_please_try_again': 'Failed to delete account. Please try again.',
      'settings_family_accounts': 'Family & Accounts',
      'settings_get_notified_at_each_solar_term': 'Get notified at each solar term',
      'settings_getting_started': 'Getting Started',
      'settings_health_info_push': 'Health Info Push',
      'settings_memory_cleared': 'Memory cleared',
      'settings_notificationssettings': 'NotificationsSettings',
      'settings_privacy_data': 'Privacy & Data',
      'settings_push_wellness_knowledge_and_solar_term_update': 'Push wellness knowledge and solar term updates',
      'settings_remind_you_to_complete_daily_exercise': 'Remind you to complete daily exercise',
      'settings_remind_you_to_rest_on_time': 'Remind you to rest on time',
      'settings_reminder_time': 'Reminder Time',
      'settings_response_in_24h': 'Response in 24h',
      'settings_restore': 'Restore',
      'settings_sleep_reminder': 'Sleep Reminder',
      'settings_solar_term_alerts': 'Solar Term Alerts',
      'settings_subscription_billing': 'Subscription & Billing',
      'settings_technical_issues': 'Technical Issues',
      'shopping_add': 'Add',
      'shopping_add_6_items': 'Add 6 items',
      'shopping_add_item': 'Add Item',
      'shopping_from_your_kitchen': 'From your kitchen',
      'shopping_seasonal_essentials': 'Seasonal Essentials',
      'skills_back_to_skills': 'Back to skills',
      'skills_how_to_start': 'How to start',
      'skills_wellness_skills': 'Wellness Skills',
      'skills_what_you_could_do': 'What you could do',
      'sleep_30_min_deep_sleep': '30 Min · Deep Sleep',
      'sleep_bedtime_tales': 'Bedtime Tales',
      'sleep_currently_playing': 'Currently Playing',
      'sleep_gently_drift_into_the_world_of_dreams': 'Gently drift into the world of dreams.',
      'sleep_midnight_rainfall': 'Midnight Rainfall',
      'sleep_natures_layer': "Nature's Layer",
      'sleep_nightfall_stillness': 'Nightfall Stillness',
      'sleep_sleep_sanctuary': 'Sleep Sanctuary',
      'sleep_sleep_stories': 'Sleep Stories',
      'solar_24_solar_terms': '24 Solar Terms',
      'solar_acupressure': 'Acupressure',
      'solar_constitution_test_result': 'Constitution Test Result',
      'solar_daily_rhythm': 'Daily Rhythm',
            'solar_emotionswellness': 'EmotionsWellness',
      'solar_exercisesuggestion': 'Exercisesuggestion: ',
      'solar_mindful_meditation': 'Mindful Meditation',
      'solar_seasons_living_guide': 'SEASONS Living Guide',
      'solar_share_link_copied': 'Share link copied',
      'solar_share_result': 'Share Result',
      'solar_share_this_seasonal_inspiration': 'Share this seasonal inspiration',
      'solar_share_this_seasons_inspiration': 'Share this SEASONS inspiration',
      'solar_solar_term_essence': 'Solar Term Essence',
      'solar_solar_term_wellness_goes_further': 'Solar term wellness goes further',
      'solar_view_details': 'View Details',
      'subscription_128_personalized_health_suggestions_ready_for': '128 personalized health suggestions ready for you',
      'subscription_3_members_health_sharing': '3 members · Health sharing',
      'subscription_annual_plan': 'Annual Plan',
      'subscription_checkout': 'Checkout',
      'subscription_complete_your_subscription': 'Complete Your Subscription',
      'subscription_family_plan': 'Family Plan',
      'subscription_first_year_deal_only_054day': 'First year deal · Only ¥0.54/day',
      'subscription_flexible_cancel_anytime': 'Flexible · Cancel anytime',
      'subscription_member_benefits': 'Member Benefits',
      'subscription_membership': 'Membership',
      'subscription_monthly_plan': 'Monthly Plan',
      'subscription_over_12000_members_have_chosen_annual_plans': 'Over 12,000 members have chosen annual plans',
      'subscription_powered_by_stripe': 'Powered by Stripe',
      'subscription_proceed_to_payment': 'Proceed to Payment',
      'subscription_secure_payment': 'Secure Payment',
      'subscription_start_your_smart_wellness_journey': 'Start your smart wellness journey',
      'subscription_subscribe_now': 'Subscribe Now',
      'subscription_svip_benefits': 'SVIP Benefits',
      'welcome_northern': 'Northern',
      'welcome_or_select_manually': 'Or select manually',
      'welcome_southern': 'Southern',
      'wellness_9_body_types': '9 Body Types',
      'wellness_acupressure_wellness': 'Acupressure Wellness',
      'wellness_always_here_to_listen': 'Always here to listen',
      'wellness_best_time_to_drink': 'Best Time to Drink',
      'wellness_body_type': 'Body Type',
      'wellness_chat_with_seasons': 'Chat with SEASONS',
      'wellness_deviation': 'Deviation',
      'wellness_diet_tea_exercise_acupoints_seasonal_plans': 'Diet · Tea · Exercise · Acupoints · Seasonal Plans',
      'wellness_drug_recommendations': 'Drug Recommendations',
      'wellness_emotional_companionship': 'Emotional Companionship',
      'wellness_emotional_support': 'Emotional Support',
      'wellness_follow_the_rhythm_relax_body_and_mind': 'Follow the rhythm, relax body and mind',
      'wellness_food_therapy_teas': 'Food Therapy & Teas',
      'wellness_food_therapyrecommended': 'Food Therapyrecommended ',
      'wellness_got_it': 'Got it',
      'wellness_health_scores': 'Health Scores',
      'wellness_how_was_your_sleep_last_night': 'How was your sleep last night?',
      'wellness_lifestyle_advice': 'Lifestyle Advice',
      'wellness_massage_steps': 'Massage Steps:',
      'wellness_medical_diagnosis': 'Medical Diagnosis',
      'wellness_mindful_breathing_guide': 'Mindful Breathing Guide',
      'wellness_mindful_breathing_guide_2': '🌬️ Mindful Breathing Guide',
      'wellness_mood_scoring': 'Mood Scoring',
      'wellness_precautions': 'Precautions',
      'wellness_previous': 'Previous',
      'wellness_product_boundaries': 'Product Boundaries',
      'wellness_relief_methods': 'Relief Methods',
      'wellness_retest': 'Retest',
      'wellness_seasons_does_not_provide': 'SEASONS Does Not Provide',
      'wellness_select_area': 'Select Area',
      'wellness_select_season': 'Select Season',
      'wellness_sleep_improvement': 'Sleep Improvement',
      'wellness_solar_term_wellness': 'Solar Term Wellness',
      'wellness_specific_steps': 'Specific Steps',
      'wellness_start_guide': 'Start Guide',
      'wellness_start_test': 'Start Test',
      'wellness_suggested_categories': 'Suggested Categories',
      'wellness_symptom_analysis': 'Symptom Analysis',
      'wellness_tearecommended': 'Tearecommended ',
      'wellness_tendency': 'Tendency',
      'wellness_unlock_full_constitution_report': 'Unlock Full Constitution Report',
      'wellness_unlock_report': 'Unlock Report',
      'wellness_we_focus_on_areas_that_help_you_live_better': 'We focus on areas that help you live better',
      'wellness_what_seasons_provides': 'What SEASONS Provides',
      'wellness_your_constitution_type_is': 'Your Constitution Type is',
    },
    'ja': {
      'app_title': 'SEASONS',
      'loading': '読み込み中...',
      'error': 'エラーが発生しました',
      'retry': '再試行',
      'cancel': 'キャンセル',
      'confirm': '確認',
      'save': '保存',
      'delete': '削除',
      'edit': '編集',
      'next': '次へ',
      'skip': 'スキップ',
      'get_started': '始める',
      'nav_home': 'ホーム',
      'nav_seasons': '季節',
      'nav_library': 'ライブラリ',
      'nav_profile': 'プロフィール',
      'home_greeting_morning': 'おはようございます',
      'home_greeting_afternoon': 'こんにちは',
      'home_greeting_evening': 'こんばんは',
      'home_daily_insight': '今日のインサイト',
      'home_suggestions': 'おすすめ',
      'home_chat_entry': 'チャット',
      'home_quick_questions': 'クイック質問',
      'chat_placeholder': '考えを共有する...',
      'chat_companion': 'コンパニオン',
      'seasons_title': '季節',
      'seasons_subtitle': '自然のリズムで暮らす',
      'seasons_spring': '春',
      'seasons_summer': '夏',
      'seasons_autumn': '秋',
      'seasons_winter': '冬',
      'library_title': 'ライブラリ',
      'library_subtitle': 'ウェルネスコンテンツ',
      'reflection_title': '振り返り',
      'reflection_how_feeling': '今日の気分はどうですか？',
      'reflection_save': '振り返りを保存',
      'profile_title': 'プロフィール',
      'subscribe_title': 'プランを選択',
      'onboarding_welcome': 'SEASONSへようこそ',
      'onboarding_subtitle': '季節のウェルネスコンパニオン',
      'body_type_title': '体質',
      'wellness_title': 'ウェルネス',
      'settings_title': '設定',
      'subscription_title': 'サブスクリプション',
      'home_wellness_principle': '養生原則',
      'home_ai_assistant': 'SEASONS AIアシスタント',
      'home_reminder': 'SEASONSリマインダー',
      'home_view_wellness_chart': '時辰養生チャートを見る',
      'home_meridian_active': '経絡活発',
      'profile_brand': 'ShunShi AI',
      'profile_points': 'ポイント',
      'profile_coupons': 'クーポン',
      'profile_achievements': '実績',
      'profile_invite_title': '友達を招待してプレミアムを取得',
      'profile_invite_subtitle': '友達と一緒にウェルネスを楽しむ',
      'profile_invite_now': '今すぐ招待',
      'profile_wellness_goals': 'ウェルネス目標',
      'profile_about': 'SEASONSについて',
      'profile_slogan': '自然と調和し、心身を養う',
      'profile_guest_name': 'SEASONSフレンド',
      'profile_free_tier': 'フリーティア',
      'login_brand': 'Seasons',
      'login_subtitle': '自然と調和して生きる',
      'login_full_name': 'フルネーム',
      'login_create_account': 'アカウントを作成',
      'login_sign_in': 'サインイン',
      'login_or_continue_with': 'または',
      'login_skip': '今はスキップ',
      'login_error_empty': 'メールとパスワードを入力してください',
      'login_error_failed': 'ログインに失敗しました。もう一度お試しください。',
      'login_error_fill_fields': 'すべての項目を入力してください',
      'login_error_register_failed': '登録に失敗しました。もう一度お試しください。',
      'login_error_guest_failed': 'ゲストログインに失敗しました。',
      'login_google_sdk': 'GoogleサインインにはSDK設定が必要です',
      'login_apple_sdk': 'Appleサインインには開発者設定が必要です',
      'chat_clear_chat': 'Clear Chat',
      'chat_playing_audio': 'Playing audio...',
      'chat_cancel': 'Cancel',
      'chat_seasonal_guidance': 'Seasonal Guidance',
      'chat_a_gentle_moment_with_nature': 'A gentle moment with nature',
      'chat_dietary_care': 'Dietary Care',
      'chat_nourish_with_tremella_and_lily': 'Nourish with tremella and lily bulbs',
      'chat_rest_suggestions': 'Rest Suggestions',
      'chat_ask_about_wellness': 'Ask about wellness...',
      'seasons_chat_share_whats_on_your_mind': "Share what's on your mind...",
      'chat_failed_to_start_recording_please': 'Failed to start recording, please check microphone permission',
      'chat_solar_term_care_tips': 'Solar Term Care Tips',
      'chat_follow_natural_rhythms_harmonize_body': 'Follow natural rhythms, harmonize body and mind',
      'chat_chat_with_seasons': 'Chat with SEASONS...',
      'diary_how_does_your_body_feel': 'How does your body feel today...',
      'family_failed_to_add': 'Failed to add',
      'favorites_failed_to_remove_from_favorites': 'Failed to remove from favorites',
      'feedback_thank_you_for_your_feedback': 'Thank you for your feedback!',
      'feedback_please_describe_your_question_or': 'Please describe your question or suggestion: ...',
      'daily_checkin_for_example_did_baduanjin_today': 'For example: did Baduanjin today, drank goji berry tea...',
      'home_page_intl_try_again': 'Try again',
      'ultimate_home_deep_sleep': 'Deep Sleep',
      'ultimate_home_rest_quietly': 'Rest Quietly',
      'ultimate_home_deep_sleep_1': 'Deep Sleep',
      'ultimate_home_protect_liver': 'Protect Liver',
      'ultimate_home_deep_breathing': 'Deep Breathing',
      'ultimate_home_peaceful_sleep': 'Peaceful Sleep',
      'ultimate_home_warm_water': 'Warm Water',
      'ultimate_home_morning_activity': 'Morning Activity',
      'ultimate_home_warm_breakfast': 'Warm Breakfast',
      'ultimate_home_ginger_jujube_tea': 'Ginger Jujube Tea',
      'ultimate_home_productive_work': 'Productive Work',
      'ultimate_home_spleen_tea': 'Spleen Tea',
      'ultimate_home_midday_nap': 'Midday Nap',
      'ultimate_home_quiet_meditation': 'Quiet Meditation',
      'ultimate_home_afternoon_walk': 'Afternoon Walk',
      'ultimate_home_stay_hydrated': 'Stay Hydrated',
      'ultimate_home_moderate_exercise': 'Moderate Exercise',
      'ultimate_home_drink_warm_water': 'Drink Warm Water',
      'ultimate_home_hydrate': 'Hydrate',
      'ultimate_home_tap_heels': 'Tap Heels',
      'ultimate_home_listen_to_music': 'Listen to Music',
      'ultimate_home_floral_tea': 'Floral Tea',
      'ultimate_home_foot_soak': 'Foot Soak',
      'ultimate_home_quiet_reading': 'Quiet Reading',
      'action_guide_overlay_todays_wellness_in_progress': "Today's Wellness in Progress",
      'journal_reflection_how_does_this_season_feel': 'How does this season feel in your body...',
      'wellness_library_search_wellness_content': 'Search wellness content...',
      'login_google_signin_requires_sdk_setup': 'Google Sign-In requires SDK setup',
      'login_apple_signin_requires_apple_developer': 'Apple Sign-In requires Apple Developer setup',
      'login_google_1': 'Google',
      'login_apple_1': 'Apple',
      'login_guest_1': 'Guest',
      'seasons_onboarding_there_are_no_wrong_answers': 'There are no wrong answers.',
      'seasons_onboarding_this_helps_us_personalise_content': 'This helps us personalise content for you.',
      'seasons_onboarding_you_can_always_change_this': 'You can always change this later.',
      'feedback_issues_suggestions_experience_feedback': 'Issues, suggestions, experience feedback...',
      'privacy_cancel': 'Cancel',
      'profile_setup_enter_your_nickname': 'Enter your nickname',
      'profile_setup_for_example_often_tired_poor': 'For example: often tired, poor sleep, prone to colds...',
      'reflection_write_something': 'Write something...',
      'reflection_grateful': 'Grateful',
      'reflection_calm': 'Calm',
      'reflection_happy': 'Happy',
      'reflection_tired': 'Tired',
      'reflection_reflective': 'Reflective',
      'global_search_search_wellness_knowledge': 'Search wellness knowledge...',
      'help_center_search_for_help': 'Search for help...',
      'seasonal_shopping_ingredient_name': 'Ingredient name...',
      'solar_detail_load_failed': 'Load failed',
      'solar_term_detail_share_link_copied': 'Share link copied',
      'boundaries_the_following_are_outside_our': 'The following are outside our scope and may pose health risks',
      'wellness_home_spring_wellness_start_with_liver': 'Spring Wellness: Start with Liver Qi',
      'wellness_home_baduanjin_awaken_your_meridian_energy': 'Baduanjin: Awaken Your Meridian Energy',
      'wellness_home_five_flavors_five_organs_balance': 'Five Flavors, Five Organs: Balance Your Diet',
      'wellness_home_search_wellness_plans_seasonal_recipes': 'Search wellness plans, seasonal recipes...',
    },
    'zh': {
      'app_title': '顺时',
      'loading': '加载中...',
      'error': '出了点问题',
      'retry': '重试',
      'cancel': '取消',
      'confirm': '确认',
      'save': '保存',
      'delete': '删除',
      'edit': '编辑',
      'next': '下一步',
      'skip': '跳过',
      'back': '返回',
      'done': '完成',
      'close': '关闭',
      'search': '搜索',
      'get_started': '开始使用',
      'learn_more': '了解更多',
      'view_all': '查看全部',
      'no_data': '暂无数据',
      'coming_soon': '即将推出',
      'nav_home': '首页',
      'nav_seasons': '节气',
      'nav_library': '养生库',
      'nav_profile': '我的',
      'nav_chat': '对话',
      'nav_wellness': '养生',
      'home_greeting_morning': '早上好',
      'home_greeting_afternoon': '下午好',
      'home_greeting_evening': '晚上好',
      'home_daily_insight': '今日洞察',
      'home_suggestions': '温柔建议',
      'home_chat_entry': '与顾问对话',
      'home_quick_questions': '快捷提问',
      'home_today_plan': '今日计划',
      'home_checkin': '每日打卡',
      'solar_terms_title': '二十四节气',
      'solar_wellness': '节气养生',
      'seasons_title': '节气',
      'chat_title': '养生顾问',
      'chat_placeholder': '分享你的想法...',
      'food_therapy': '食疗',
      'food_therapy_title': '节气食疗',
      'tea_recommendation': '茶饮推荐',
      'constitution_title': '体质测试',
      'constitution_test': '体质测试',
      'meditation_title': '冥想',
      'exercise_title': '运动',
      'library_title': '养生库',
      'reflection_title': '每日反思',
      'journal_title': '养生日记',
      'profile_title': '个人中心',
      'settings_title': '设置',
      'subscription_title': '会员订阅',
      'subscribe_restore': '恢复购买',
      'family_title': '家庭养生',
      'wellness_title': '养生',
      'wellness_dashboard': '养生看板',
      'login_title': '登录',
      'register_title': '注册',
      'notification_title': '通知',
      'ai_companion': 'AI养生顾问',
      'ai_disclaimer': '以上建议仅供参考，不能替代医生诊断。',
      'home_wellness_principle': '养生原则',
      'home_ai_assistant': '顺时 AI 助手',
      'home_reminder': '顺时提醒',
      'home_view_wellness_chart': '查看完整时辰养生图',
      'home_meridian_active': '经络当令',
      'profile_brand': '顺时AI',
      'profile_points': '积分',
      'profile_coupons': '优惠券',
      'profile_achievements': '成就',
      'profile_invite_title': '邀请好友，获得会员',
      'profile_invite_subtitle': '与好友同行，共享养生',
      'profile_invite_now': '立即邀请',
      'profile_wellness_goals': '养生目标',
      'profile_about': '关于顺时',
      'profile_slogan': '顺应自然，滋养身心',
      'profile_guest_name': '顺时之友',
      'profile_free_tier': '免费版',
      'login_brand': '顺时',
      'login_subtitle': '与自然和谐共处',
      'login_full_name': '姓名',
      'login_create_account': '创建账号',
      'login_sign_in': '登录',
      'login_or_continue_with': '或使用以下方式',
      'login_skip': '暂时跳过',
      'login_error_empty': '请输入邮箱和密码',
      'login_error_failed': '登录失败，请重试',
      'login_error_fill_fields': '请填写所有字段',
      'login_error_register_failed': '注册失败，请重试',
      'login_error_guest_failed': '游客登录失败，请重试',
      'login_google_sdk': 'Google登录需要SDK配置',
      'login_apple_sdk': 'Apple登录需要开发者配置',
      'solar_dietary_care': '饮食调养',
      'solar_exercise': '运动',
      'solar_seasonal_teas': '节气茶饮',
      'constitution_start_test': '开始体质测试',
      'constitution_your_type': '你的体质',
      'constitution_report_locked': '解锁完整报告',
      'constitution_retake': '重新测试',
      'constitution_view_report': '查看完整报告',
      'chat_quota_used': '今日对话次数已用完',
      'chat_upgrade_now': '立即升级',
      'chat_later': '稍后再说',
      'chat_health_notice': '健康安全提示',
      'chat_understand': '我已了解',
      'settings_push_notifications': '推送通知',
      'settings_senior_mode': '长辈模式',
      'settings_senior_desc': '提供更大字体和简化界面',
      'settings_clear_cache': '清除缓存',
      'settings_cloud_zen': '云水禅心',
      'favorites_remove_failed': '取消收藏失败',
      'feedback_type': '反馈类型',
      'feedback_rating': '评分',
      'feedback_content': '反馈内容',
      'feedback_submit_btn': '提交反馈',
      'feedback_thanks': '感谢您的反馈！',
      'family_no_members': '还没有家庭成员',
      'family_diff_plans': '根据每位成员的体质提供差异化养生方案',
      'wellness_studio': '养生工作室',
      'wellness_editors_picks': '编辑精选',
      'about_app_name': '顺时 · SEASONS',
      'about_version': '版本 2.4.0',
      'about_description': '顺时是一款基于中医养生理论的智能健康伴侣。结合二十四节气、十二时辰和九种体质，为每位用户提供个性化的养生建议。',
      'meditation_breathing': '呼吸中的变化',
      'meditation_checkin': '打卡',
      'checkin_sanctuary': '数字静修所',
      'checkin_morning': '清晨宁静',
      'checkin_streak_current': '当前连续',
      'checkin_energy_question': '今天的能量状态如何？',
      'checkin_energy_level': '能量等级',
      'search_popular': '热门搜索',
      'subscription_recommended': '推荐',
      'subscription_annual_deal': '年度优惠',
      'subscription_per_year': '/年',
      'notif_settings_title': '通知设置',
      'solar_diet_wellness': '饮食养生',
      'solar_next_term': '下一个节气：{name}',
      'exercise_qigong': '气功运动',
      'exercise_type': '运动类型',
      'exercise_all': '全部',
      'exercise_movement': '动作分解',
      'exercise_start_ai': '开始AI引导练习',
      'exercise_no_content': '暂无内容',
    
      'chat_clear_chat': 'Clear Chat',
      'chat_playing_audio': 'Playing audio...',
      'chat_cancel': 'Cancel',
      'chat_seasonal_guidance': 'Seasonal Guidance',
      'chat_a_gentle_moment_with_nature': 'A gentle moment with nature',
      'chat_dietary_care': 'Dietary Care',
      'chat_nourish_with_tremella_and_lily': 'Nourish with tremella and lily bulbs',
      'chat_rest_suggestions': 'Rest Suggestions',
      'chat_ask_about_wellness': 'Ask about wellness...',
      'seasons_chat_share_whats_on_your_mind': "Share what's on your mind...",
      'chat_failed_to_start_recording_please': 'Failed to start recording, please check microphone permission',
      'chat_solar_term_care_tips': 'Solar Term Care Tips',
      'chat_follow_natural_rhythms_harmonize_body': 'Follow natural rhythms, harmonize body and mind',
      'chat_chat_with_seasons': 'Chat with SEASONS...',
      'diary_how_does_your_body_feel': 'How does your body feel today...',
      'family_failed_to_add': 'Failed to add',
      'favorites_failed_to_remove_from_favorites': 'Failed to remove from favorites',
      'feedback_thank_you_for_your_feedback': 'Thank you for your feedback!',
      'feedback_please_describe_your_question_or': 'Please describe your question or suggestion: ...',
      'daily_checkin_for_example_did_baduanjin_today': 'For example: did Baduanjin today, drank goji berry tea...',
      'home_page_intl_try_again': 'Try again',
      'ultimate_home_deep_sleep': 'Deep Sleep',
      'ultimate_home_rest_quietly': 'Rest Quietly',
      'ultimate_home_deep_sleep_1': 'Deep Sleep',
      'ultimate_home_protect_liver': 'Protect Liver',
      'ultimate_home_deep_breathing': 'Deep Breathing',
      'ultimate_home_peaceful_sleep': 'Peaceful Sleep',
      'ultimate_home_warm_water': 'Warm Water',
      'ultimate_home_morning_activity': 'Morning Activity',
      'ultimate_home_warm_breakfast': 'Warm Breakfast',
      'ultimate_home_ginger_jujube_tea': 'Ginger Jujube Tea',
      'ultimate_home_productive_work': 'Productive Work',
      'ultimate_home_spleen_tea': 'Spleen Tea',
      'ultimate_home_midday_nap': 'Midday Nap',
      'ultimate_home_quiet_meditation': 'Quiet Meditation',
      'ultimate_home_afternoon_walk': 'Afternoon Walk',
      'ultimate_home_stay_hydrated': 'Stay Hydrated',
      'ultimate_home_moderate_exercise': 'Moderate Exercise',
      'ultimate_home_drink_warm_water': 'Drink Warm Water',
      'ultimate_home_hydrate': 'Hydrate',
      'ultimate_home_tap_heels': 'Tap Heels',
      'ultimate_home_listen_to_music': 'Listen to Music',
      'ultimate_home_floral_tea': 'Floral Tea',
      'ultimate_home_foot_soak': 'Foot Soak',
      'ultimate_home_quiet_reading': 'Quiet Reading',
      'action_guide_overlay_todays_wellness_in_progress': "Today's Wellness in Progress",
      'journal_reflection_how_does_this_season_feel': 'How does this season feel in your body...',
      'wellness_library_search_wellness_content': 'Search wellness content...',
      'login_google_signin_requires_sdk_setup': 'Google Sign-In requires SDK setup',
      'login_apple_signin_requires_apple_developer': 'Apple Sign-In requires Apple Developer setup',
      'login_google_1': 'Google',
      'login_apple_1': 'Apple',
      'login_guest_1': 'Guest',
      'seasons_onboarding_there_are_no_wrong_answers': 'There are no wrong answers.',
      'seasons_onboarding_this_helps_us_personalise_content': 'This helps us personalise content for you.',
      'seasons_onboarding_you_can_always_change_this': 'You can always change this later.',
      'feedback_issues_suggestions_experience_feedback': 'Issues, suggestions, experience feedback...',
      'privacy_cancel': 'Cancel',
      'profile_setup_enter_your_nickname': 'Enter your nickname',
      'profile_setup_for_example_often_tired_poor': 'For example: often tired, poor sleep, prone to colds...',
      'reflection_write_something': 'Write something...',
      'reflection_grateful': 'Grateful',
      'reflection_calm': 'Calm',
      'reflection_happy': 'Happy',
      'reflection_tired': 'Tired',
      'reflection_reflective': 'Reflective',
      'global_search_search_wellness_knowledge': 'Search wellness knowledge...',
      'help_center_search_for_help': 'Search for help...',
      'seasonal_shopping_ingredient_name': 'Ingredient name...',
      'solar_detail_load_failed': 'Load failed',
      'solar_term_detail_share_link_copied': 'Share link copied',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  String t(String key, {Map<String, String>? params}) {
    String text = get(key);
    if (params != null) {
      params.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }
    return text;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ja', 'zh'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

