"""full_schema_all_tables

Revision ID: 120c73a3479b
Revises: 
Create Date: 2026-04-27 21:22:49.127077
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.database  # noqa: F401 — needed for GUID type


# revision identifiers, used by Alembic.
revision: str = '120c73a3479b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sa_acupoint_favorites',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('acupoint_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_acupoint_favorites_acupoint_id'), 'sa_acupoint_favorites', ['acupoint_id'], unique=False)
    op.create_index(op.f('ix_sa_acupoint_favorites_user_id'), 'sa_acupoint_favorites', ['user_id'], unique=False)
    op.create_table('sa_acupoints',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('meridian', sa.String(length=50), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('location_image', sa.String(length=500), nullable=True),
    sa.Column('technique', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('indications', sa.JSON(), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('suitable_constitutions', sa.JSON(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('time_of_day', sa.String(length=50), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_acupoints_code'), 'sa_acupoints', ['code'], unique=True)
    op.create_table('sa_article_bookmarks',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('article_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_article_bookmarks_article_id'), 'sa_article_bookmarks', ['article_id'], unique=False)
    op.create_index(op.f('ix_sa_article_bookmarks_user_id'), 'sa_article_bookmarks', ['user_id'], unique=False)
    op.create_table('sa_articles',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_blocks', sa.JSON(), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('read_time_min', sa.Integer(), nullable=True),
    sa.Column('tcm_concepts', sa.JSON(), nullable=True),
    sa.Column('related_recipes', sa.JSON(), nullable=True),
    sa.Column('related_exercises', sa.JSON(), nullable=True),
    sa.Column('related_teas', sa.JSON(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_audio_play_history',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('track_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('progress_sec', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('played_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_audio_play_history_track_id'), 'sa_audio_play_history', ['track_id'], unique=False)
    op.create_index(op.f('ix_sa_audio_play_history_user_id'), 'sa_audio_play_history', ['user_id'], unique=False)
    op.create_table('sa_audio_tracks',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('narrator', sa.String(length=100), nullable=True),
    sa.Column('tcm_concept', sa.String(length=100), nullable=True),
    sa.Column('suitable_constitutions', sa.JSON(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('time_of_day', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_calorie_goals',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('daily_calories', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_calorie_goals_user_id'), 'sa_calorie_goals', ['user_id'], unique=True)
    op.create_table('sa_chat_conversations',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_chat_conversations_conversation_id'), 'sa_chat_conversations', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_sa_chat_conversations_user_id'), 'sa_chat_conversations', ['user_id'], unique=False)
    op.create_table('sa_chat_memories',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('source_message_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_chat_memories_user_id'), 'sa_chat_memories', ['user_id'], unique=False)
    op.create_table('sa_chat_messages',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.String(length=20), nullable=True),
    sa.Column('feedback_reason', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_chat_messages_conversation_id'), 'sa_chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sa_chat_messages_user_id'), 'sa_chat_messages', ['user_id'], unique=False)
    op.create_table('sa_checkin_records',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('consecutive_days', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'checkin_date', name='uq_user_checkin')
    )
    op.create_index(op.f('ix_sa_checkin_records_user_id'), 'sa_checkin_records', ['user_id'], unique=False)
    op.create_table('sa_community_posts',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_community_posts_user_id'), 'sa_community_posts', ['user_id'], unique=False)
    op.create_table('sa_constitution_questions',
    sa.Column('question_text', sa.Text(), nullable=False, comment='题目文本'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='判断哪种体质'),
    sa.Column('options', sa.JSON(), nullable=True, comment='选项列表 [{text, score_map}]'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_constitutions',
    sa.Column('name', sa.String(length=50), nullable=False, comment='体质名称（如 气虚质）'),
    sa.Column('description', sa.Text(), nullable=True, comment='体质描述'),
    sa.Column('characteristics', sa.JSON(), nullable=True, comment='典型特征（JSON）'),
    sa.Column('diet_advice', sa.JSON(), nullable=True, comment='饮食建议（JSON）'),
    sa.Column('tea_advice', sa.JSON(), nullable=True, comment='茶饮建议（JSON）'),
    sa.Column('exercise_advice', sa.JSON(), nullable=True, comment='运动建议（JSON）'),
    sa.Column('avoid_list', sa.JSON(), nullable=True, comment='禁忌列表（JSON）'),
    sa.Column('season_advice', sa.JSON(), nullable=True, comment='四季建议（JSON）'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_content_items',
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('subtitle', sa.String(length=300), nullable=True, comment='副标题'),
    sa.Column('content_type', sa.String(length=30), nullable=False, comment='内容类型: food/tea/acupoint/exercise/sleep/emotion/solar_term/constitution'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细描述'),
    sa.Column('steps', sa.JSON(), nullable=True, comment='步骤列表（JSON 数组）'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='时长（分钟）'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签（JSON 数组）'),
    sa.Column('season', sa.String(length=20), nullable=True, comment='适用季节: spring/summer/autumn/winter/all'),
    sa.Column('constitution', sa.String(length=200), nullable=True, comment='适用体质（多个逗号分隔）'),
    sa.Column('best_time', sa.String(length=100), nullable=True, comment='最佳使用时间'),
    sa.Column('caution', sa.Text(), nullable=True, comment='注意事项'),
    sa.Column('is_premium', sa.Boolean(), nullable=False, comment='是否为付费内容'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='内容状态: draft/published/archived'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览次数'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞次数'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_content_tags',
    sa.Column('name', sa.String(length=100), nullable=False, comment='标签名称（唯一）'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='标签分类'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='使用次数'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sa_coupons',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('coupon_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('is_redeemed', sa.Boolean(), nullable=True),
    sa.Column('redeemed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('issued_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_coupons_code'), 'sa_coupons', ['code'], unique=True)
    op.create_index(op.f('ix_sa_coupons_user_id'), 'sa_coupons', ['user_id'], unique=False)
    op.create_table('sa_dream_logs',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dream_quality', sa.String(length=32), nullable=True),
    sa.Column('emotions', sa.JSON(), nullable=True),
    sa.Column('sleep_time', sa.String(length=5), nullable=True),
    sa.Column('wake_time', sa.String(length=5), nullable=True),
    sa.Column('body_symptoms', sa.JSON(), nullable=True),
    sa.Column('tcm_analysis', sa.JSON(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_dream_logs_user_id'), 'sa_dream_logs', ['user_id'], unique=False)
    op.create_table('sa_exercise_favorites',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('exercise_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_exercise_favorites_exercise_id'), 'sa_exercise_favorites', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_sa_exercise_favorites_user_id'), 'sa_exercise_favorites', ['user_id'], unique=False)
    op.create_table('sa_exercise_logs',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('exercise_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('mood_after', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_exercise_logs_exercise_id'), 'sa_exercise_logs', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_sa_exercise_logs_user_id'), 'sa_exercise_logs', ['user_id'], unique=False)
    op.create_table('sa_exercises',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('target_body_parts', sa.JSON(), nullable=True),
    sa.Column('suitable_constitutions', sa.JSON(), nullable=True),
    sa.Column('unsuitable_conditions', sa.JSON(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('time_of_day', sa.String(length=50), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('instructor', sa.String(length=100), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_expert_questions',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('expert_id', sa.String(length=64), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('answered_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_expert_questions_user_id'), 'sa_expert_questions', ['user_id'], unique=False)
    op.create_table('sa_family_members',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('owner_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('member_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('relationship', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_feature_flags',
    sa.Column('flag_name', sa.String(length=100), nullable=False, comment='功能名称（唯一）'),
    sa.Column('flag_type', sa.String(length=20), nullable=False, comment='开关类型: bool/percentage/variant'),
    sa.Column('value', sa.JSON(), nullable=True, comment='开关值（JSON）'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='功能描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('target_users', sa.JSON(), nullable=True, comment='目标用户白名单（JSON，可空表示所有用户）'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag_name')
    )
    op.create_table('sa_gift_cards',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('denomination', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_redeemed', sa.Boolean(), nullable=True),
    sa.Column('redeemed_by', sa.String(length=64), nullable=True),
    sa.Column('redeemed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_gift_cards_buyer_id'), 'sa_gift_cards', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_sa_gift_cards_code'), 'sa_gift_cards', ['code'], unique=True)
    op.create_table('sa_gift_orders',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_gift_orders_buyer_id'), 'sa_gift_orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_sa_gift_orders_recipient_id'), 'sa_gift_orders', ['recipient_id'], unique=False)
    op.create_table('sa_gratitude_entries',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('mood', sa.String(length=16), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_gratitude_entries_user_id'), 'sa_gratitude_entries', ['user_id'], unique=False)
    op.create_table('sa_habits',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=True),
    sa.Column('target_days', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('total_checkins', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_habits_user_id'), 'sa_habits', ['user_id'], unique=False)
    op.create_table('sa_journal_entries',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('mood_score', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('body_condition', sa.JSON(), nullable=True),
    sa.Column('weather', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('ai_insight', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_journal_entries_date'), 'sa_journal_entries', ['date'], unique=False)
    op.create_index(op.f('ix_sa_journal_entries_user_id'), 'sa_journal_entries', ['user_id'], unique=False)
    op.create_table('sa_journal_photos',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('journal_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_journal_photos_journal_id'), 'sa_journal_photos', ['journal_id'], unique=False)
    op.create_table('sa_live_class_bookings',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('booked_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('attended_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_live_class_bookings_class_id'), 'sa_live_class_bookings', ['class_id'], unique=False)
    op.create_index(op.f('ix_sa_live_class_bookings_user_id'), 'sa_live_class_bookings', ['user_id'], unique=False)
    op.create_table('sa_meal_logs',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('foods', sa.JSON(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein_g', sa.Float(), nullable=True),
    sa.Column('total_carbs_g', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_meal_logs_user_id'), 'sa_meal_logs', ['user_id'], unique=False)
    op.create_table('sa_membership_benefit_usage',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('benefit_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('limit_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_membership_benefit_usage_user_id'), 'sa_membership_benefit_usage', ['user_id'], unique=False)
    op.create_table('sa_membership_plans',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cny', sa.Float(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sa_menstrual_cycles',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('period_length', sa.Integer(), nullable=True),
    sa.Column('flow_level', sa.String(length=16), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_menstrual_cycles_user_id'), 'sa_menstrual_cycles', ['user_id'], unique=False)
    op.create_table('sa_menstrual_settings',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('avg_cycle_length', sa.Integer(), nullable=True),
    sa.Column('avg_period_length', sa.Integer(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=True),
    sa.Column('reminder_days_before', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_menstrual_settings_user_id'), 'sa_menstrual_settings', ['user_id'], unique=True)
    op.create_table('sa_onboarding_progress',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('constitution_result', sa.String(length=30), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_onboarding_progress_user_id'), 'sa_onboarding_progress', ['user_id'], unique=True)
    op.create_table('sa_prompt_versions',
    sa.Column('prompt_type', sa.String(length=20), nullable=False, comment='Prompt 类型: core/policy/task'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('content', sa.Text(), nullable=True, comment='Prompt 内容'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否为当前活跃版本'),
    sa.Column('model_filter', sa.JSON(), nullable=True, comment='适用模型过滤条件（JSON）'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_recipe_favorites',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('recipe_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_recipe_favorites_recipe_id'), 'sa_recipe_favorites', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_sa_recipe_favorites_user_id'), 'sa_recipe_favorites', ['user_id'], unique=False)
    op.create_table('sa_recipes',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('nutrition', sa.JSON(), nullable=True),
    sa.Column('tcm_effect', sa.String(length=100), nullable=True),
    sa.Column('suitable_constitutions', sa.JSON(), nullable=True),
    sa.Column('unsuitable_constitutions', sa.JSON(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('prep_time_min', sa.Integer(), nullable=True),
    sa.Column('cook_time_min', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_reminder_logs',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('reminder_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('triggered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('acknowledged_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('snoozed', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_reminder_logs_reminder_id'), 'sa_reminder_logs', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_sa_reminder_logs_user_id'), 'sa_reminder_logs', ['user_id'], unique=False)
    op.create_table('sa_reminders',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('days', sa.JSON(), nullable=True),
    sa.Column('shichen', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sound', sa.String(length=50), nullable=True),
    sa.Column('vibration', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('snooze_min', sa.Integer(), nullable=True),
    sa.Column('related_content_id', sa.String(length=64), nullable=True),
    sa.Column('last_triggered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_reminders_user_id'), 'sa_reminders', ['user_id'], unique=False)
    op.create_table('sa_smart_alarms',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('alarm_type', sa.String(length=32), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('days', sa.JSON(), nullable=True),
    sa.Column('sound', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('shichen_aligned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_smart_alarms_user_id'), 'sa_smart_alarms', ['user_id'], unique=False)
    op.create_table('sa_solar_terms',
    sa.Column('name', sa.String(length=50), nullable=False, comment='节气名称（如 春分）'),
    sa.Column('name_en', sa.String(length=50), nullable=True, comment='英文名称'),
    sa.Column('term_date', sa.Date(), nullable=True, comment='该年日期'),
    sa.Column('month', sa.Integer(), nullable=True, comment='月份'),
    sa.Column('day', sa.Integer(), nullable=True, comment='日期'),
    sa.Column('season', sa.String(length=20), nullable=False, comment='所属季节: spring/summer/autumn/winter'),
    sa.Column('description', sa.Text(), nullable=True, comment='节气描述'),
    sa.Column('diet_advice', sa.JSON(), nullable=True, comment='饮食建议（JSON）'),
    sa.Column('tea_advice', sa.JSON(), nullable=True, comment='茶饮建议（JSON）'),
    sa.Column('exercise_advice', sa.JSON(), nullable=True, comment='运动建议（JSON）'),
    sa.Column('acupoint_advice', sa.JSON(), nullable=True, comment='穴位建议（JSON）'),
    sa.Column('emotion_advice', sa.JSON(), nullable=True, comment='情绪调理建议（JSON）'),
    sa.Column('seven_day_plan', sa.JSON(), nullable=True, comment='七日养生计划（JSON）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active/inactive'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_subscription_products',
    sa.Column('product_id', sa.String(length=100), nullable=False, comment='产品 SKU（如 shunshi_yangxin_yearly）'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='产品名称'),
    sa.Column('tier', sa.String(length=20), nullable=False, comment='会员等级: free/yangxin/yiyang/jiahe'),
    sa.Column('platform', sa.String(length=20), nullable=True, comment='支付平台: alipay/apple/google'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='价格'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='货币（默认 CNY）'),
    sa.Column('duration_days', sa.Integer(), nullable=False, comment='有效天数'),
    sa.Column('max_family_seats', sa.Integer(), nullable=False, comment='最大家庭席位数'),
    sa.Column('features', sa.JSON(), nullable=True, comment='权益列表（JSON）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='产品状态: active/inactive'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('sa_tea_favorites',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('tea_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_tea_favorites_tea_id'), 'sa_tea_favorites', ['tea_id'], unique=False)
    op.create_index(op.f('ix_sa_tea_favorites_user_id'), 'sa_tea_favorites', ['user_id'], unique=False)
    op.create_table('sa_teas',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('brewing_method', sa.JSON(), nullable=True),
    sa.Column('tcm_effect', sa.String(length=100), nullable=True),
    sa.Column('suitable_constitutions', sa.JSON(), nullable=True),
    sa.Column('unsuitable_constitutions', sa.JSON(), nullable=True),
    sa.Column('suitable_season', sa.String(length=20), nullable=True),
    sa.Column('suitable_time', sa.String(length=50), nullable=True),
    sa.Column('caffeine_level', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_user_auth',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('auth_identifier', sa.String(length=255), nullable=False),
    sa.Column('auth_credential', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_user_badges',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('badge_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('awarded_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_index(op.f('ix_sa_user_badges_user_id'), 'sa_user_badges', ['user_id'], unique=False)
    op.create_table('sa_user_devices',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('push_token', sa.String(length=500), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('os_version', sa.String(length=20), nullable=True),
    sa.Column('last_active_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_user_feedback',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('app_version', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_user_feedback_user_id'), 'sa_user_feedback', ['user_id'], unique=False)
    op.create_table('sa_user_memberships',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cancelled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_user_memberships_user_id'), 'sa_user_memberships', ['user_id'], unique=False)
    op.create_table('sa_user_points',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_user_points_user_id'), 'sa_user_points', ['user_id'], unique=True)
    op.create_table('sa_users',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('constitution_type', sa.String(length=20), nullable=True),
    sa.Column('constitution_tested_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('constitution_scores', sa.JSON(), nullable=True),
    sa.Column('membership_level', sa.SmallInteger(), nullable=True),
    sa.Column('membership_expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('membership_auto_renew', sa.Boolean(), nullable=True),
    sa.Column('consecutive_days', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('user_level', sa.SmallInteger(), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('preferred_wake_time', sa.String(length=10), nullable=True),
    sa.Column('preferred_sleep_time', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('sa_water_goals',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('goal_ml', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_water_goals_user_id'), 'sa_water_goals', ['user_id'], unique=True)
    op.create_table('sa_water_logs',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('logged_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_water_logs_user_id'), 'sa_water_logs', ['user_id'], unique=False)
    op.create_table('sa_wearable_syncs',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=30), nullable=True),
    sa.Column('sync_date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('heart_rate_avg', sa.Float(), nullable=True),
    sa.Column('heart_rate_resting', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_deep_hours', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('spo2_avg', sa.Float(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('tcm_insights', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_wearable_syncs_user_id'), 'sa_wearable_syncs', ['user_id'], unique=False)
    op.create_table('sa_weight_goals',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('weeks', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_weight_goals_user_id'), 'sa_weight_goals', ['user_id'], unique=True)
    op.create_table('sa_weight_logs',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_weight_logs_user_id'), 'sa_weight_logs', ['user_id'], unique=False)
    op.create_table('sa_care_status',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID（唯一，一个用户一条记录）'),
    sa.Column('current_status', sa.String(length=20), nullable=False, comment='当前状态: stable/tired/needs_attention'),
    sa.Column('presence_level', sa.String(length=20), nullable=False, comment='活跃程度: present/normal/retreating'),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True, comment='最后更新时间'),
    sa.Column('trend', sa.String(length=20), nullable=False, comment='状态趋势: improving/stable/declining'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_care_status_user_id'), 'sa_care_status', ['user_id'], unique=True)
    op.create_table('sa_community_comments',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('post_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['sa_community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_community_comments_user_id'), 'sa_community_comments', ['user_id'], unique=False)
    op.create_table('sa_constitution_results',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID'),
    sa.Column('primary_type', sa.String(length=50), nullable=False, comment='主要体质（如 气虚质）'),
    sa.Column('secondary_types', sa.JSON(), nullable=True, comment='倾向体质列表（JSON 数组）'),
    sa.Column('scores', sa.JSON(), nullable=True, comment='各体质分数（JSON）'),
    sa.Column('advice', sa.JSON(), nullable=True, comment='AI 生成的建议（JSON）'),
    sa.Column('version', sa.Integer(), nullable=False, comment='问卷版本号'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_constitution_results_user_id'), 'sa_constitution_results', ['user_id'], unique=False)
    op.create_table('sa_content_media',
    sa.Column('content_id', sa.String(), nullable=False, comment='关联内容 ID'),
    sa.Column('media_type', sa.String(length=20), nullable=False, comment='媒体类型: image/video/audio'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='媒体 URL（OSS）'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True, comment='缩略图 URL'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='时长（秒，视频/音频）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['content_id'], ['sa_content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_content_media_content_id'), 'sa_content_media', ['content_id'], unique=False)
    op.create_table('sa_content_tag_relations',
    sa.Column('content_id', sa.String(), nullable=False, comment='关联内容 ID'),
    sa.Column('tag_id', sa.String(), nullable=False, comment='关联标签 ID'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['content_id'], ['sa_content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['sa_content_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_content_tag_relations_content_id'), 'sa_content_tag_relations', ['content_id'], unique=False)
    op.create_index(op.f('ix_sa_content_tag_relations_tag_id'), 'sa_content_tag_relations', ['tag_id'], unique=False)
    op.create_table('sa_conversation_sessions',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='会话标题（可空，AI 生成）'),
    sa.Column('skill_chain', sa.JSON(), nullable=True, comment='使用的 skill 链列表（JSON）'),
    sa.Column('model_used', sa.String(length=100), nullable=True, comment='使用的模型名称'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='消息数量'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='最后消息时间'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='会话状态: active/archived/deleted'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_conversation_sessions_user_id'), 'sa_conversation_sessions', ['user_id'], unique=False)
    op.create_table('sa_diary_entries',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID'),
    sa.Column('entry_date', sa.Date(), nullable=False, comment='日记日期'),
    sa.Column('mood', sa.Integer(), nullable=True, comment='心情评分 (1-5)'),
    sa.Column('sleep_quality', sa.Integer(), nullable=True, comment='睡眠质量 (1-5)'),
    sa.Column('sleep_hours', sa.Float(), nullable=True, comment='睡眠时长（小时）'),
    sa.Column('diet', sa.Text(), nullable=True, comment='饮食记录'),
    sa.Column('water_glasses', sa.Integer(), nullable=True, comment='饮水杯数'),
    sa.Column('exercise', sa.Text(), nullable=True, comment='运动记录'),
    sa.Column('exercise_minutes', sa.Integer(), nullable=True, comment='运动时长（分钟）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('ai_comment', sa.Text(), nullable=True, comment='AI 评语（可空）'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_diary_entries_entry_date'), 'sa_diary_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_sa_diary_entries_user_id'), 'sa_diary_entries', ['user_id'], unique=False)
    op.create_table('sa_family_relations',
    sa.Column('inviter_id', app.db.types.GUID(length=36), nullable=False, comment='邀请人 ID'),
    sa.Column('invitee_id', app.db.types.GUID(length=36), nullable=False, comment='被邀请人 ID'),
    sa.Column('relation_type', sa.String(length=20), nullable=False, comment='关系类型: parent/spouse/child/guardian'),
    sa.Column('invite_code', sa.String(length=50), nullable=True, comment='邀请码'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/active/inactive'),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True, comment='绑定时间'),
    sa.Column('can_view_status', sa.Boolean(), nullable=False, comment='是否可查看健康状态（默认 True）'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='权限配置（JSON）'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['invitee_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_family_relations_invitee_id'), 'sa_family_relations', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_sa_family_relations_inviter_id'), 'sa_family_relations', ['inviter_id'], unique=False)
    op.create_table('sa_follow_ups',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID'),
    sa.Column('intent', sa.String(length=50), nullable=False, comment='意图（如 sleep_check/emotion_check/water_remind）'),
    sa.Column('content', sa.Text(), nullable=True, comment='提醒内容'),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True, comment='到期时间'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/sent/dismissed/completed'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: high/normal/low'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源: chat/schedule/manual'),
    sa.Column('snooze_count', sa.Integer(), nullable=False, comment='贪睡次数（默认 0）'),
    sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True, comment='最后提醒时间'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_follow_ups_user_id'), 'sa_follow_ups', ['user_id'], unique=False)
    op.create_table('sa_habit_checkins',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('habit_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['sa_habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_habit_checkins_user_id'), 'sa_habit_checkins', ['user_id'], unique=False)
    op.create_table('sa_monthly_reports',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID'),
    sa.Column('month', sa.String(length=7), nullable=False, comment='月份（如 2026-03）'),
    sa.Column('summary', sa.Text(), nullable=True, comment='月总结'),
    sa.Column('insights', sa.JSON(), nullable=True, comment='洞察分析（JSON）'),
    sa.Column('suggestions', sa.JSON(), nullable=True, comment='建议列表（JSON）'),
    sa.Column('mood_trend', sa.JSON(), nullable=True, comment='心情趋势（JSON）'),
    sa.Column('sleep_trend', sa.JSON(), nullable=True, comment='睡眠趋势（JSON）'),
    sa.Column('generated_by', sa.String(length=100), nullable=True, comment='生成模型名称'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_monthly_reports_user_id'), 'sa_monthly_reports', ['user_id'], unique=False)
    op.create_table('sa_notifications',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='通知类型: solar_term/follow_up/sleep/water/exercise/family'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='通知标题'),
    sa.Column('body', sa.String(length=1000), nullable=True, comment='通知内容'),
    sa.Column('data', sa.JSON(), nullable=True, comment='附加数据（JSON）'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='发送时间'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='已读时间（可空，未读）'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='通知渠道: push/local/in_app'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_notifications_user_id'), 'sa_notifications', ['user_id'], unique=False)
    op.create_table('sa_scheduled_notifications',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='通知类型'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='通知标题'),
    sa.Column('body', sa.String(length=1000), nullable=True, comment='通知内容'),
    sa.Column('data', sa.JSON(), nullable=True, comment='附加数据'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False, comment='计划发送时间'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='实际发送时间'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/sent/cancelled'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_scheduled_notifications_user_id'), 'sa_scheduled_notifications', ['user_id'], unique=False)
    op.create_table('sa_solar_term_contents',
    sa.Column('solar_term_id', sa.String(), nullable=False, comment='关联节气 ID'),
    sa.Column('content_id', sa.String(), nullable=False, comment='关联内容 ID'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['content_id'], ['sa_content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solar_term_id'], ['sa_solar_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_solar_term_contents_content_id'), 'sa_solar_term_contents', ['content_id'], unique=False)
    op.create_index(op.f('ix_sa_solar_term_contents_solar_term_id'), 'sa_solar_term_contents', ['solar_term_id'], unique=False)
    op.create_table('sa_subscription_orders',
    sa.Column('order_no', sa.String(length=100), nullable=False, comment='订单号（唯一）'),
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID'),
    sa.Column('product_id', sa.String(), nullable=True, comment='关联产品 ID'),
    sa.Column('platform', sa.String(length=20), nullable=True, comment='支付平台: alipay/apple/google'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='实际支付金额'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='货币'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='订单状态: pending/paid/failed/refunded/expired'),
    sa.Column('transaction_id', sa.String(length=255), nullable=True, comment='第三方交易号'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='支付时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间'),
    sa.Column('refund_reason', sa.String(length=500), nullable=True, comment='退款原因（可空）'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['product_id'], ['sa_subscription_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_sa_subscription_orders_product_id'), 'sa_subscription_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_sa_subscription_orders_user_id'), 'sa_subscription_orders', ['user_id'], unique=False)
    op.create_table('sa_weekly_reports',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID'),
    sa.Column('week_start', sa.Date(), nullable=False, comment='周开始日期'),
    sa.Column('week_end', sa.Date(), nullable=False, comment='周结束日期'),
    sa.Column('summary', sa.Text(), nullable=True, comment='周总结'),
    sa.Column('insights', sa.JSON(), nullable=True, comment='洞察分析（JSON）'),
    sa.Column('suggestions', sa.JSON(), nullable=True, comment='建议列表（JSON）'),
    sa.Column('mood_trend', sa.JSON(), nullable=True, comment='心情趋势（JSON）'),
    sa.Column('sleep_trend', sa.JSON(), nullable=True, comment='睡眠趋势（JSON）'),
    sa.Column('generated_by', sa.String(length=100), nullable=True, comment='生成模型名称'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_weekly_reports_user_id'), 'sa_weekly_reports', ['user_id'], unique=False)
    op.create_table('sa_ai_audit_logs',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=True, comment='关联用户 ID'),
    sa.Column('session_id', sa.String(), nullable=True, comment='关联对话会话 ID（可空）'),
    sa.Column('provider_name', sa.String(length=50), nullable=False, comment='AI 提供商名称'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('prompt_versions', sa.JSON(), nullable=True, comment='使用的 prompt 版本列表（JSON）'),
    sa.Column('skill_chain', sa.JSON(), nullable=True, comment='skill 链（JSON）'),
    sa.Column('tokens_in', sa.Integer(), nullable=False, comment='输入 token 数'),
    sa.Column('tokens_out', sa.Integer(), nullable=False, comment='输出 token 数'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='响应延迟（毫秒）'),
    sa.Column('safety_flag', sa.String(length=50), nullable=True, comment='安全标记'),
    sa.Column('route_decision', sa.JSON(), nullable=True, comment='路由决策（JSON）'),
    sa.Column('response_status', sa.String(length=20), nullable=False, comment='响应状态: success/failed/timeout/filtered'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息（可空）'),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False, comment='调用成本（美元）'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['sa_conversation_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_ai_audit_logs_session_id'), 'sa_ai_audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_sa_ai_audit_logs_user_id'), 'sa_ai_audit_logs', ['user_id'], unique=False)
    op.create_table('sa_conversation_messages',
    sa.Column('session_id', sa.String(), nullable=False, comment='关联会话 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=True, comment='消息内容'),
    sa.Column('message_type', sa.String(length=30), nullable=False, comment='消息类型: text/system_notice/content_card/safe_mode_notice/follow_up_card'),
    sa.Column('content_cards', sa.JSON(), nullable=True, comment='内容卡片数据（可空）'),
    sa.Column('safety_flag', sa.String(length=20), nullable=False, comment='安全标记: none/medical/risk/crisis'),
    sa.Column('model_used', sa.String(length=100), nullable=True, comment='使用的模型名称'),
    sa.Column('tokens_in', sa.Integer(), nullable=False, comment='输入 token 数'),
    sa.Column('tokens_out', sa.Integer(), nullable=False, comment='输出 token 数'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='响应延迟（毫秒）'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['sa_conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_conversation_messages_session_id'), 'sa_conversation_messages', ['session_id'], unique=False)
    op.create_table('sa_user_subscriptions',
    sa.Column('user_id', app.db.types.GUID(length=36), nullable=False, comment='关联用户 ID（同一用户同时仅一个活跃订阅）'),
    sa.Column('tier', sa.String(length=20), nullable=False, comment='会员等级: free/yangxin/yiyang/jiahe'),
    sa.Column('order_id', sa.String(), nullable=True, comment='关联订单 ID'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True, comment='订阅开始时间'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='订阅结束时间'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='订阅状态: active/expired/cancelled'),
    sa.Column('auto_renew', sa.Boolean(), nullable=False, comment='是否自动续费'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='订阅来源: purchase/restore/gift/admin'),
    sa.Column('id', sa.String(), nullable=False, comment='UUID 主键'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已软删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['order_id'], ['sa_subscription_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['sa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_user_subscriptions_user_id'), 'sa_user_subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sa_user_subscriptions_user_id'), table_name='sa_user_subscriptions')
    op.drop_table('sa_user_subscriptions')
    op.drop_index(op.f('ix_sa_conversation_messages_session_id'), table_name='sa_conversation_messages')
    op.drop_table('sa_conversation_messages')
    op.drop_index(op.f('ix_sa_ai_audit_logs_user_id'), table_name='sa_ai_audit_logs')
    op.drop_index(op.f('ix_sa_ai_audit_logs_session_id'), table_name='sa_ai_audit_logs')
    op.drop_table('sa_ai_audit_logs')
    op.drop_index(op.f('ix_sa_weekly_reports_user_id'), table_name='sa_weekly_reports')
    op.drop_table('sa_weekly_reports')
    op.drop_index(op.f('ix_sa_subscription_orders_user_id'), table_name='sa_subscription_orders')
    op.drop_index(op.f('ix_sa_subscription_orders_product_id'), table_name='sa_subscription_orders')
    op.drop_table('sa_subscription_orders')
    op.drop_index(op.f('ix_sa_solar_term_contents_solar_term_id'), table_name='sa_solar_term_contents')
    op.drop_index(op.f('ix_sa_solar_term_contents_content_id'), table_name='sa_solar_term_contents')
    op.drop_table('sa_solar_term_contents')
    op.drop_index(op.f('ix_sa_scheduled_notifications_user_id'), table_name='sa_scheduled_notifications')
    op.drop_table('sa_scheduled_notifications')
    op.drop_index(op.f('ix_sa_notifications_user_id'), table_name='sa_notifications')
    op.drop_table('sa_notifications')
    op.drop_index(op.f('ix_sa_monthly_reports_user_id'), table_name='sa_monthly_reports')
    op.drop_table('sa_monthly_reports')
    op.drop_index(op.f('ix_sa_habit_checkins_user_id'), table_name='sa_habit_checkins')
    op.drop_table('sa_habit_checkins')
    op.drop_index(op.f('ix_sa_follow_ups_user_id'), table_name='sa_follow_ups')
    op.drop_table('sa_follow_ups')
    op.drop_index(op.f('ix_sa_family_relations_inviter_id'), table_name='sa_family_relations')
    op.drop_index(op.f('ix_sa_family_relations_invitee_id'), table_name='sa_family_relations')
    op.drop_table('sa_family_relations')
    op.drop_index(op.f('ix_sa_diary_entries_user_id'), table_name='sa_diary_entries')
    op.drop_index(op.f('ix_sa_diary_entries_entry_date'), table_name='sa_diary_entries')
    op.drop_table('sa_diary_entries')
    op.drop_index(op.f('ix_sa_conversation_sessions_user_id'), table_name='sa_conversation_sessions')
    op.drop_table('sa_conversation_sessions')
    op.drop_index(op.f('ix_sa_content_tag_relations_tag_id'), table_name='sa_content_tag_relations')
    op.drop_index(op.f('ix_sa_content_tag_relations_content_id'), table_name='sa_content_tag_relations')
    op.drop_table('sa_content_tag_relations')
    op.drop_index(op.f('ix_sa_content_media_content_id'), table_name='sa_content_media')
    op.drop_table('sa_content_media')
    op.drop_index(op.f('ix_sa_constitution_results_user_id'), table_name='sa_constitution_results')
    op.drop_table('sa_constitution_results')
    op.drop_index(op.f('ix_sa_community_comments_user_id'), table_name='sa_community_comments')
    op.drop_table('sa_community_comments')
    op.drop_index(op.f('ix_sa_care_status_user_id'), table_name='sa_care_status')
    op.drop_table('sa_care_status')
    op.drop_index(op.f('ix_sa_weight_logs_user_id'), table_name='sa_weight_logs')
    op.drop_table('sa_weight_logs')
    op.drop_index(op.f('ix_sa_weight_goals_user_id'), table_name='sa_weight_goals')
    op.drop_table('sa_weight_goals')
    op.drop_index(op.f('ix_sa_wearable_syncs_user_id'), table_name='sa_wearable_syncs')
    op.drop_table('sa_wearable_syncs')
    op.drop_index(op.f('ix_sa_water_logs_user_id'), table_name='sa_water_logs')
    op.drop_table('sa_water_logs')
    op.drop_index(op.f('ix_sa_water_goals_user_id'), table_name='sa_water_goals')
    op.drop_table('sa_water_goals')
    op.drop_table('sa_users')
    op.drop_index(op.f('ix_sa_user_points_user_id'), table_name='sa_user_points')
    op.drop_table('sa_user_points')
    op.drop_index(op.f('ix_sa_user_memberships_user_id'), table_name='sa_user_memberships')
    op.drop_table('sa_user_memberships')
    op.drop_index(op.f('ix_sa_user_feedback_user_id'), table_name='sa_user_feedback')
    op.drop_table('sa_user_feedback')
    op.drop_table('sa_user_devices')
    op.drop_index(op.f('ix_sa_user_badges_user_id'), table_name='sa_user_badges')
    op.drop_table('sa_user_badges')
    op.drop_table('sa_user_auth')
    op.drop_table('sa_teas')
    op.drop_index(op.f('ix_sa_tea_favorites_user_id'), table_name='sa_tea_favorites')
    op.drop_index(op.f('ix_sa_tea_favorites_tea_id'), table_name='sa_tea_favorites')
    op.drop_table('sa_tea_favorites')
    op.drop_table('sa_subscription_products')
    op.drop_table('sa_solar_terms')
    op.drop_index(op.f('ix_sa_smart_alarms_user_id'), table_name='sa_smart_alarms')
    op.drop_table('sa_smart_alarms')
    op.drop_index(op.f('ix_sa_reminders_user_id'), table_name='sa_reminders')
    op.drop_table('sa_reminders')
    op.drop_index(op.f('ix_sa_reminder_logs_user_id'), table_name='sa_reminder_logs')
    op.drop_index(op.f('ix_sa_reminder_logs_reminder_id'), table_name='sa_reminder_logs')
    op.drop_table('sa_reminder_logs')
    op.drop_table('sa_recipes')
    op.drop_index(op.f('ix_sa_recipe_favorites_user_id'), table_name='sa_recipe_favorites')
    op.drop_index(op.f('ix_sa_recipe_favorites_recipe_id'), table_name='sa_recipe_favorites')
    op.drop_table('sa_recipe_favorites')
    op.drop_table('sa_prompt_versions')
    op.drop_index(op.f('ix_sa_onboarding_progress_user_id'), table_name='sa_onboarding_progress')
    op.drop_table('sa_onboarding_progress')
    op.drop_index(op.f('ix_sa_menstrual_settings_user_id'), table_name='sa_menstrual_settings')
    op.drop_table('sa_menstrual_settings')
    op.drop_index(op.f('ix_sa_menstrual_cycles_user_id'), table_name='sa_menstrual_cycles')
    op.drop_table('sa_menstrual_cycles')
    op.drop_table('sa_membership_plans')
    op.drop_index(op.f('ix_sa_membership_benefit_usage_user_id'), table_name='sa_membership_benefit_usage')
    op.drop_table('sa_membership_benefit_usage')
    op.drop_index(op.f('ix_sa_meal_logs_user_id'), table_name='sa_meal_logs')
    op.drop_table('sa_meal_logs')
    op.drop_index(op.f('ix_sa_live_class_bookings_user_id'), table_name='sa_live_class_bookings')
    op.drop_index(op.f('ix_sa_live_class_bookings_class_id'), table_name='sa_live_class_bookings')
    op.drop_table('sa_live_class_bookings')
    op.drop_index(op.f('ix_sa_journal_photos_journal_id'), table_name='sa_journal_photos')
    op.drop_table('sa_journal_photos')
    op.drop_index(op.f('ix_sa_journal_entries_user_id'), table_name='sa_journal_entries')
    op.drop_index(op.f('ix_sa_journal_entries_date'), table_name='sa_journal_entries')
    op.drop_table('sa_journal_entries')
    op.drop_index(op.f('ix_sa_habits_user_id'), table_name='sa_habits')
    op.drop_table('sa_habits')
    op.drop_index(op.f('ix_sa_gratitude_entries_user_id'), table_name='sa_gratitude_entries')
    op.drop_table('sa_gratitude_entries')
    op.drop_index(op.f('ix_sa_gift_orders_recipient_id'), table_name='sa_gift_orders')
    op.drop_index(op.f('ix_sa_gift_orders_buyer_id'), table_name='sa_gift_orders')
    op.drop_table('sa_gift_orders')
    op.drop_index(op.f('ix_sa_gift_cards_code'), table_name='sa_gift_cards')
    op.drop_index(op.f('ix_sa_gift_cards_buyer_id'), table_name='sa_gift_cards')
    op.drop_table('sa_gift_cards')
    op.drop_table('sa_feature_flags')
    op.drop_table('sa_family_members')
    op.drop_index(op.f('ix_sa_expert_questions_user_id'), table_name='sa_expert_questions')
    op.drop_table('sa_expert_questions')
    op.drop_table('sa_exercises')
    op.drop_index(op.f('ix_sa_exercise_logs_user_id'), table_name='sa_exercise_logs')
    op.drop_index(op.f('ix_sa_exercise_logs_exercise_id'), table_name='sa_exercise_logs')
    op.drop_table('sa_exercise_logs')
    op.drop_index(op.f('ix_sa_exercise_favorites_user_id'), table_name='sa_exercise_favorites')
    op.drop_index(op.f('ix_sa_exercise_favorites_exercise_id'), table_name='sa_exercise_favorites')
    op.drop_table('sa_exercise_favorites')
    op.drop_index(op.f('ix_sa_dream_logs_user_id'), table_name='sa_dream_logs')
    op.drop_table('sa_dream_logs')
    op.drop_index(op.f('ix_sa_coupons_user_id'), table_name='sa_coupons')
    op.drop_index(op.f('ix_sa_coupons_code'), table_name='sa_coupons')
    op.drop_table('sa_coupons')
    op.drop_table('sa_content_tags')
    op.drop_table('sa_content_items')
    op.drop_table('sa_constitutions')
    op.drop_table('sa_constitution_questions')
    op.drop_index(op.f('ix_sa_community_posts_user_id'), table_name='sa_community_posts')
    op.drop_table('sa_community_posts')
    op.drop_index(op.f('ix_sa_checkin_records_user_id'), table_name='sa_checkin_records')
    op.drop_table('sa_checkin_records')
    op.drop_index(op.f('ix_sa_chat_messages_user_id'), table_name='sa_chat_messages')
    op.drop_index(op.f('ix_sa_chat_messages_conversation_id'), table_name='sa_chat_messages')
    op.drop_table('sa_chat_messages')
    op.drop_index(op.f('ix_sa_chat_memories_user_id'), table_name='sa_chat_memories')
    op.drop_table('sa_chat_memories')
    op.drop_index(op.f('ix_sa_chat_conversations_user_id'), table_name='sa_chat_conversations')
    op.drop_index(op.f('ix_sa_chat_conversations_conversation_id'), table_name='sa_chat_conversations')
    op.drop_table('sa_chat_conversations')
    op.drop_index(op.f('ix_sa_calorie_goals_user_id'), table_name='sa_calorie_goals')
    op.drop_table('sa_calorie_goals')
    op.drop_table('sa_audio_tracks')
    op.drop_index(op.f('ix_sa_audio_play_history_user_id'), table_name='sa_audio_play_history')
    op.drop_index(op.f('ix_sa_audio_play_history_track_id'), table_name='sa_audio_play_history')
    op.drop_table('sa_audio_play_history')
    op.drop_table('sa_articles')
    op.drop_index(op.f('ix_sa_article_bookmarks_user_id'), table_name='sa_article_bookmarks')
    op.drop_index(op.f('ix_sa_article_bookmarks_article_id'), table_name='sa_article_bookmarks')
    op.drop_table('sa_article_bookmarks')
    op.drop_index(op.f('ix_sa_acupoints_code'), table_name='sa_acupoints')
    op.drop_table('sa_acupoints')
    op.drop_index(op.f('ix_sa_acupoint_favorites_user_id'), table_name='sa_acupoint_favorites')
    op.drop_index(op.f('ix_sa_acupoint_favorites_acupoint_id'), table_name='sa_acupoint_favorites')
    op.drop_table('sa_acupoint_favorites')
    # ### end Alembic commands ###
